<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0d00ed06f40452de82a38adc9943003a
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'AirRoofers\\Identity\\' => 20,
            'AirRoofers\\PlatformCore\\' => 24,
            'AirRoofers\\Operations\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'AirRoofers\\Identity\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'AirRoofers\\PlatformCore\\' => 
        array (
            0 => __DIR__ . '/..' . '/airroofers/platform-core/src',
        ),
        'AirRoofers\\Operations\\' => 
        array (
            0 => __DIR__ . '/..' . '/airroofers/operations/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0d00ed06f40452de82a38adc9943003a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0d00ed06f40452de82a38adc9943003a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0d00ed06f40452de82a38adc9943003a::$classMap;

        }, null, ClassLoader::class);
    }
}
