<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit10e4a331a2f74b48f8ca18d736293369
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'AirRoofers\\Products\\' => 21,
            'AirRoofers\\PlatformCore\\' => 24,
            'AirRoofers\\Operations\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'AirRoofers\\Products\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'AirRoofers\\PlatformCore\\' => 
        array (
            0 => __DIR__ . '/..' . '/airroofers/platform-core/src',
        ),
        'AirRoofers\\Operations\\' => 
        array (
            0 => __DIR__ . '/..' . '/airroofers/operations/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit10e4a331a2f74b48f8ca18d736293369::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit10e4a331a2f74b48f8ca18d736293369::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit10e4a331a2f74b48f8ca18d736293369::$classMap;

        }, null, ClassLoader::class);
    }
}
