<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AirRoofers\\Identity\\' => array($baseDir . '/src'),
    'AirRoofers\\PlatformCore\\' => array($vendorDir . '/airroofers/platform-core/src'),
    'AirRoofers\\Operations\\' => array($vendorDir . '/airroofers/operations/src'),
);
