const fs = require('fs');
const path = require('path');
const dir = 'D:\\ujomor-platform\\products\\ugondu\\server\\shared\\locales';
const LANGS = ['en', 'fr', 'es', 'de', 'it'];
const P = 'uppie.adapter.aws.';
const cat = {
  'invalid_condition': ["The '{type}' condition is invalid or cannot be expressed in an IAM policy.", "La condition « {type} » est invalide ou ne peut pas être exprimée dans une politique IAM.", "La condición '{type}' no es válida o no se puede expresar en una política de IAM.", "Die Bedingung '{type}' ist ungültig oder lässt sich in einer IAM-Richtlinie nicht ausdrücken.", "La condizione '{type}' non è valida o non può essere espressa in una policy IAM."],
  'sdk_unavailable': ['The AWS client library is not available: {error}', "La bibliothèque cliente AWS n'est pas disponible : {error}", 'La biblioteca cliente de AWS no está disponible: {error}', 'Die AWS-Clientbibliothek ist nicht verfügbar: {error}', 'La libreria client AWS non è disponibile: {error}'],
  'last_accessed_timeout': ['The service last-accessed report did not complete in time.', "Le rapport de dernier accès aux services n'a pas été généré à temps.", 'El informe de último acceso a los servicios no se completó a tiempo.', 'Der Bericht zum letzten Servicezugriff wurde nicht rechtzeitig fertiggestellt.', "Il report dell'ultimo accesso ai servizi non è stato completato in tempo."],
  'attach_error': ['Failed to attach the policy: {error}', 'Échec du rattachement de la politique : {error}', 'Error al asociar la política: {error}', 'Die Richtlinie konnte nicht zugewiesen werden: {error}', 'Impossibile associare la policy: {error}'],
  'detach_error': ['Failed to detach the policy: {error}', 'Échec du détachement de la politique : {error}', 'Error al desasociar la política: {error}', 'Die Richtlinie konnte nicht entfernt werden: {error}', 'Impossibile dissociare la policy: {error}'],
  'update_error': ['Failed to update the policy: {error}', 'Échec de la mise à jour de la politique : {error}', 'Error al actualizar la política: {error}', 'Die Richtlinie konnte nicht aktualisiert werden: {error}', 'Impossibile aggiornare la policy: {error}'],
  'clone_error': ['Failed to clone the policy: {error}', 'Échec du clonage de la politique : {error}', 'Error al clonar la política: {error}', 'Die Richtlinie konnte nicht geklont werden: {error}', 'Impossibile clonare la policy: {error}'],
  'retire_error': ['Failed to retire the policy: {error}', 'Échec du retrait de la politique : {error}', 'Error al retirar la política: {error}', 'Die Richtlinie konnte nicht außer Betrieb genommen werden: {error}', 'Impossibile ritirare la policy: {error}'],
  'restore_error': ['Failed to restore the policy: {error}', 'Échec de la restauration de la politique : {error}', 'Error al restaurar la política: {error}', 'Die Richtlinie konnte nicht wiederhergestellt werden: {error}', 'Impossibile ripristinare la policy: {error}'],
  'reconcile_error': ['Failed to reconcile the policy: {error}', 'Échec du rapprochement de la politique : {error}', 'Error al conciliar la política: {error}', 'Die Richtlinie konnte nicht abgeglichen werden: {error}', 'Impossibile riconciliare la policy: {error}'],
  'restore_no_reference': ['Restore failed: the retirement certificate has no rollback reference.', "Échec de la restauration : le certificat de retrait ne contient aucune référence de restauration.", 'Error al restaurar: el certificado de retiro no contiene ninguna referencia de restauración.', 'Wiederherstellung fehlgeschlagen: Das Außerbetriebnahme-Zertifikat enthält keine Rollback-Referenz.', 'Ripristino non riuscito: il certificato di ritiro non contiene alcun riferimento di ripristino.'],
  'restore_invalid_snapshot': ["The rollback snapshot does not match the policy '{arn}'.", "L'instantané de restauration ne correspond pas à la politique « {arn} ».", "La instantánea de restauración no coincide con la política '{arn}'.", "Der Rollback-Snapshot passt nicht zur Richtlinie '{arn}'.", "Lo snapshot di ripristino non corrisponde alla policy '{arn}'."],
  'retire_in_use': ["Policy '{arn}' is still attached to {count} identity(ies); detach it before retiring.", "La politique « {arn} » est encore attachée à {count} identité(s) ; détachez-la avant de la retirer.", "La política '{arn}' sigue asociada a {count} identidad(es); desasóciela antes de retirarla.", "Die Richtlinie '{arn}' ist noch {count} Identität(en) zugewiesen; entfernen Sie diese Zuweisungen vor der Außerbetriebnahme.", "La policy '{arn}' è ancora associata a {count} identità; dissociarla prima del ritiro."],
  'protected_policy': ["Policy '{arn}' is AWS-managed and cannot be modified, retired or restored.", "La politique « {arn} » est gérée par AWS et ne peut être ni modifiée, ni retirée, ni restaurée.", "La política '{arn}' está administrada por AWS y no se puede modificar, retirar ni restaurar.", "Die Richtlinie '{arn}' wird von AWS verwaltet und kann weder geändert, außer Betrieb genommen noch wiederhergestellt werden.", "La policy '{arn}' è gestita da AWS e non può essere modificata, ritirata o ripristinata."],
  'invalid_principal': ["Invalid principal '{principal}': expected an IAM user, group or role ARN.", "Principal invalide « {principal} » : un ARN d'utilisateur, de groupe ou de rôle IAM est attendu.", "Principal no válido '{principal}': se esperaba un ARN de usuario, grupo o rol de IAM.", "Ungültiger Principal '{principal}': Erwartet wird der ARN eines IAM-Benutzers, einer IAM-Gruppe oder einer IAM-Rolle.", "Principal non valido '{principal}': è previsto l'ARN di un utente, gruppo o ruolo IAM."],
  'invalid_policy_arn': ["Invalid policy ARN '{arn}'.", "ARN de politique invalide « {arn} ».", "ARN de política no válido '{arn}'.", "Ungültiger Richtlinien-ARN '{arn}'.", "ARN di policy non valido '{arn}'."],
  'invalid_name': ["Invalid policy name '{name}': use 1-128 letters, digits and the characters + = , . @ _ -.", "Nom de politique invalide « {name} » : utilisez 1 à 128 lettres, chiffres et les caractères + = , . @ _ -.", "Nombre de política no válido '{name}': use de 1 a 128 letras, dígitos y los caracteres + = , . @ _ -.", "Ungültiger Richtlinienname '{name}': Verwenden Sie 1 bis 128 Buchstaben, Ziffern und die Zeichen + = , . @ _ -.", "Nome di policy non valido '{name}': usare da 1 a 128 lettere, cifre e i caratteri + = , . @ _ -."],
  'invalid_rule': ["Invalid rule for '{scope}': at least one operation is required.", "Règle invalide pour « {scope} » : au moins une opération est requise.", "Regla no válida para '{scope}': se requiere al menos una operación.", "Ungültige Regel für '{scope}': Mindestens eine Operation ist erforderlich.", "Regola non valida per '{scope}': è richiesta almeno un'operazione."],
  'policy_exists_different': ["A policy '{arn}' already exists with different permissions.", "Une politique « {arn} » existe déjà avec des autorisations différentes.", "Ya existe una política '{arn}' con permisos diferentes.", "Eine Richtlinie '{arn}' existiert bereits mit anderen Berechtigungen.", "Esiste già una policy '{arn}' con autorizzazioni diverse."],
  'conflict_explanation': ["An Allow and a Deny for {subject} overlap ('{allowScope}' and '{denyScope}'); the explicit Deny takes precedence.", "Une autorisation et un refus pour {subject} se chevauchent (« {allowScope} » et « {denyScope} ») ; le refus explicite l'emporte.", "Una regla Allow y una Deny para {subject} se solapan ('{allowScope}' y '{denyScope}'); prevalece la denegación explícita.", "Eine Allow- und eine Deny-Regel für {subject} überschneiden sich ('{allowScope}' und '{denyScope}'); die explizite Verweigerung hat Vorrang.", "Un'autorizzazione e un divieto per {subject} si sovrappongono ('{allowScope}' e '{denyScope}'); prevale il divieto esplicito."],
  'validate.no_document': ['The native document is missing.', 'Le document natif est absent.', 'Falta el documento nativo.', 'Das native Dokument fehlt.', 'Il documento nativo è assente.'],
  'validate.invalid_version': ["Unsupported policy language version '{version}'; use 2012-10-17.", "Version du langage de politique non prise en charge « {version} » ; utilisez 2012-10-17.", "Versión del lenguaje de políticas no admitida '{version}'; use 2012-10-17.", "Nicht unterstützte Version der Richtliniensprache '{version}'; verwenden Sie 2012-10-17.", "Versione del linguaggio delle policy non supportata '{version}'; usare 2012-10-17."],
  'validate.no_statements': ['The policy contains no statements.', 'La politique ne contient aucune instruction.', 'La política no contiene ninguna instrucción.', 'Die Richtlinie enthält keine Anweisungen.', 'La policy non contiene alcuna istruzione.'],
  'validate.invalid_effect': ["Invalid statement effect '{effect}': use Allow or Deny.", "Effet d'instruction invalide « {effect} » : utilisez Allow ou Deny.", "Efecto de instrucción no válido '{effect}': use Allow o Deny.", "Ungültiger Anweisungseffekt '{effect}': Verwenden Sie Allow oder Deny.", "Effetto dell'istruzione non valido '{effect}': usare Allow o Deny."],
  'validate.invalid_action': ["Invalid action '{action}': expected <service>:<operation>.", "Action invalide « {action} » : format attendu <service>:<opération>.", "Acción no válida '{action}': se esperaba <servicio>:<operación>.", "Ungültige Aktion '{action}': Erwartet wird <Dienst>:<Operation>.", "Azione non valida '{action}': formato atteso <servizio>:<operazione>."],
  'validate.invalid_resource': ["Invalid resource '{resource}': expected * or an ARN.", "Ressource invalide « {resource} » : * ou un ARN est attendu.", "Recurso no válido '{resource}': se esperaba * o un ARN.", "Ungültige Ressource '{resource}': Erwartet wird * oder ein ARN.", "Risorsa non valida '{resource}': è previsto * o un ARN."],
  'validate.admin_wildcard': ['An Allow statement grants every action on every resource (*:*), which violates least privilege.', 'Une instruction Allow accorde toutes les actions sur toutes les ressources (*:*), ce qui viole le principe du moindre privilège.', 'Una instrucción Allow concede todas las acciones sobre todos los recursos (*:*), lo que infringe el mínimo privilegio.', 'Eine Allow-Anweisung gewährt alle Aktionen auf allen Ressourcen (*:*) und verstößt damit gegen das Prinzip der minimalen Rechte.', "Un'istruzione Allow concede tutte le azioni su tutte le risorse (*:*), violando il principio del privilegio minimo."],
  'validate.service_wildcard': ["The action '{action}' grants every operation of a service; prefer explicit operations.", "L'action « {action} » accorde toutes les opérations d'un service ; privilégiez des opérations explicites.", "La acción '{action}' concede todas las operaciones de un servicio; prefiera operaciones explícitas.", "Die Aktion '{action}' gewährt alle Operationen eines Dienstes; bevorzugen Sie explizite Operationen.", "L'azione '{action}' concede tutte le operazioni di un servizio; preferire operazioni esplicite."],
  'validate.too_large': ['The policy is {size} characters, above the {limit}-character limit.', 'La politique compte {size} caractères, au-delà de la limite de {limit} caractères.', 'La política tiene {size} caracteres, por encima del límite de {limit} caracteres.', 'Die Richtlinie umfasst {size} Zeichen und überschreitet das Limit von {limit} Zeichen.', 'La policy è di {size} caratteri, oltre il limite di {limit} caratteri.'],
  'validate.digest_mismatch': ['The policy digest does not match its document.', 'Le condensat de la politique ne correspond pas à son document.', 'El resumen de la política no coincide con su documento.', 'Der Richtlinien-Digest stimmt nicht mit dem Dokument überein.', 'Il digest della policy non corrisponde al documento.'],
};
const setNested = (obj, dotted, value) => {
  const parts = dotted.split('.'); let o = obj;
  for (let i = 0; i < parts.length - 1; i++) { if (typeof o[parts[i]] !== 'object' || o[parts[i]] === null) o[parts[i]] = {}; o = o[parts[i]]; }
  o[parts[parts.length - 1]] = value;
};
LANGS.forEach((lang, idx) => {
  const p = path.join(dir, `${lang}.json`);
  const obj = JSON.parse(fs.readFileSync(p, 'utf8'));
  for (const [k, v] of Object.entries(cat)) setNested(obj, P + k, v[idx]);
  fs.writeFileSync(p, JSON.stringify(obj, null, 2) + '\n', 'utf8');
});
console.log('written', Object.keys(cat).length, 'keys x 5 locales (overwrite-capable)');
