const fs = require('fs');
const path = require('path');
const dir = 'D:\\ujomor-platform\\products\\ugondu\\server\\shared\\locales';
const LANGS = ['en', 'fr', 'es', 'de', 'it'];
const P = 'uppie.adapter.azure.';
// key -> [en, fr, es, de, it]
const cat = {
  'sdk_unavailable': ['The Azure client library is not available: {error}', "La bibliothèque cliente Azure n'est pas disponible : {error}", 'La biblioteca cliente de Azure no está disponible: {error}', 'Die Azure-Clientbibliothek ist nicht verfügbar: {error}', 'La libreria client di Azure non è disponibile: {error}'],
  'attach_error': ['Failed to assign the role: {error}', "Échec de l'attribution du rôle : {error}", 'Error al asignar el rol: {error}', 'Die Rolle konnte nicht zugewiesen werden: {error}', "Impossibile assegnare il ruolo: {error}"],
  'detach_error': ['Failed to remove the role assignment: {error}', "Échec de la suppression de l'attribution de rôle : {error}", 'Error al quitar la asignación de rol: {error}', 'Die Rollenzuweisung konnte nicht entfernt werden: {error}', "Impossibile rimuovere l'assegnazione del ruolo: {error}"],
  'update_error': ['Failed to update the role: {error}', 'Échec de la mise à jour du rôle : {error}', 'Error al actualizar el rol: {error}', 'Die Rolle konnte nicht aktualisiert werden: {error}', 'Impossibile aggiornare il ruolo: {error}'],
  'clone_error': ['Failed to clone the role: {error}', 'Échec du clonage du rôle : {error}', 'Error al clonar el rol: {error}', 'Die Rolle konnte nicht geklont werden: {error}', 'Impossibile clonare il ruolo: {error}'],
  'retire_error': ['Failed to retire the role: {error}', 'Échec du retrait du rôle : {error}', 'Error al retirar el rol: {error}', 'Die Rolle konnte nicht außer Betrieb genommen werden: {error}', 'Impossibile ritirare il ruolo: {error}'],
  'restore_error': ['Failed to restore the role: {error}', 'Échec de la restauration du rôle : {error}', 'Error al restaurar el rol: {error}', 'Die Rolle konnte nicht wiederhergestellt werden: {error}', 'Impossibile ripristinare il ruolo: {error}'],
  'reconcile_error': ['Failed to reconcile the rules: {error}', 'Échec de la réconciliation des règles : {error}', 'Error al conciliar las reglas: {error}', 'Die Regeln konnten nicht abgeglichen werden: {error}', 'Impossibile riconciliare le regole: {error}'],
  'invalid_scope': ["Invalid scope '{scope}': expected a management group, subscription, resource group or resource path.", "Périmètre invalide « {scope} » : un chemin de groupe d'administration, d'abonnement, de groupe de ressources ou de ressource est attendu.", "Ámbito no válido '{scope}': se esperaba una ruta de grupo de administración, suscripción, grupo de recursos o recurso.", "Ungültiger Bereich '{scope}': Erwartet wird ein Pfad für Verwaltungsgruppe, Abonnement, Ressourcengruppe oder Ressource.", "Ambito non valido '{scope}': è previsto il percorso di un gruppo di gestione, una sottoscrizione, un gruppo di risorse o una risorsa."],
  'invalid_role_id': ["Invalid role definition id '{id}'.", "Identifiant de définition de rôle invalide « {id} ».", "Identificador de definición de rol no válido '{id}'.", "Ungültige Rollendefinitions-ID '{id}'.", "ID di definizione del ruolo non valido '{id}'."],
  'invalid_principal': ["Invalid principal '{principal}': expected an object id, optionally prefixed with User:, Group:, ServicePrincipal:, ForeignGroup: or Device:.", "Principal invalide « {principal} » : un identifiant d'objet est attendu, éventuellement préfixé par User:, Group:, ServicePrincipal:, ForeignGroup: ou Device:.", "Principal no válido '{principal}': se esperaba un id de objeto, opcionalmente con el prefijo User:, Group:, ServicePrincipal:, ForeignGroup: o Device:.", "Ungültiger Principal '{principal}': Erwartet wird eine Objekt-ID, optional mit dem Präfix User:, Group:, ServicePrincipal:, ForeignGroup: oder Device:.", "Principal non valido '{principal}': è previsto un ID oggetto, facoltativamente con prefisso User:, Group:, ServicePrincipal:, ForeignGroup: o Device:."],
  'deny_unsupported': ["Rule '{ruleId}' is a Deny rule; Azure deny assignments are system-managed and cannot be created.", "La règle « {ruleId} » est une règle Deny ; les affectations de refus Azure sont gérées par le système et ne peuvent pas être créées.", "La regla '{ruleId}' es una regla Deny; las asignaciones de denegación de Azure las administra el sistema y no se pueden crear.", "Die Regel '{ruleId}' ist eine Deny-Regel; Azure-Verweigerungszuweisungen werden vom System verwaltet und können nicht erstellt werden.", "La regola '{ruleId}' è una regola Deny; le assegnazioni di negazione di Azure sono gestite dal sistema e non possono essere create."],
  'condition_unsupported': ["Rule '{ruleId}' has conditions or constraints that Azure role assignments cannot enforce.", "La règle « {ruleId} » comporte des conditions ou contraintes que les attributions de rôle Azure ne peuvent pas appliquer.", "La regla '{ruleId}' tiene condiciones o restricciones que las asignaciones de rol de Azure no pueden aplicar.", "Die Regel '{ruleId}' enthält Bedingungen oder Einschränkungen, die Azure-Rollenzuweisungen nicht durchsetzen können.", "La regola '{ruleId}' ha condizioni o vincoli che le assegnazioni di ruolo di Azure non possono applicare."],
  'validity_unsupported': ["Rule '{ruleId}' expires; Azure role assignments have no expiry (use a time-bound activation service).", "La règle « {ruleId} » expire ; les attributions de rôle Azure n'ont pas d'expiration (utilisez un service d'activation limitée dans le temps).", "La regla '{ruleId}' caduca; las asignaciones de rol de Azure no tienen vencimiento (use un servicio de activación con límite de tiempo).", "Die Regel '{ruleId}' läuft ab; Azure-Rollenzuweisungen haben kein Ablaufdatum (verwenden Sie einen zeitlich begrenzten Aktivierungsdienst).", "La regola '{ruleId}' scade; le assegnazioni di ruolo di Azure non hanno scadenza (usare un servizio di attivazione a tempo)."],
  'invalid_rule': ["Invalid rule '{ruleId}': at least one operation is required.", "Règle invalide « {ruleId} » : au moins une opération est requise.", "Regla no válida '{ruleId}': se requiere al menos una operación.", "Ungültige Regel '{ruleId}': Mindestens eine Operation ist erforderlich.", "Regola non valida '{ruleId}': è richiesta almeno un'operazione."],
  'no_rules': ['At least one rule is required to build a role.', 'Au moins une règle est requise pour créer un rôle.', 'Se requiere al menos una regla para crear un rol.', 'Zum Erstellen einer Rolle ist mindestens eine Regel erforderlich.', 'Per creare un ruolo è richiesta almeno una regola.'],
  'mixed_scopes': ['The rules span more than one scope; merging them into one role would widen access. Generate one role per scope.', "Les règles couvrent plus d'un périmètre ; les fusionner dans un seul rôle élargirait l'accès. Générez un rôle par périmètre.", 'Las reglas abarcan más de un ámbito; combinarlas en un solo rol ampliaría el acceso. Genere un rol por ámbito.', 'Die Regeln umfassen mehr als einen Bereich; ihre Zusammenführung in einer Rolle würde den Zugriff ausweiten. Erzeugen Sie eine Rolle pro Bereich.', "Le regole coprono più di un ambito; unirle in un solo ruolo amplierebbe l'accesso. Generare un ruolo per ambito."],
  'role_description': ['Managed by Ugondu (policy {digest}).', 'Géré par Ugondu (politique {digest}).', 'Administrado por Ugondu (política {digest}).', 'Verwaltet von Ugondu (Richtlinie {digest}).', 'Gestito da Ugondu (policy {digest}).'],
  'protected_role': ["Role '{id}' is a built-in role and cannot be modified, retired or restored.", "Le rôle « {id} » est un rôle intégré et ne peut être ni modifié, ni retiré, ni restauré.", "El rol '{id}' es un rol integrado y no se puede modificar, retirar ni restaurar.", "Die Rolle '{id}' ist eine integrierte Rolle und kann weder geändert, außer Betrieb genommen noch wiederhergestellt werden.", "Il ruolo '{id}' è un ruolo predefinito e non può essere modificato, ritirato o ripristinato."],
  'role_exists_different': ["A role '{id}' already exists with different permissions.", "Un rôle « {id} » existe déjà avec des autorisations différentes.", "Ya existe un rol '{id}' con permisos diferentes.", "Eine Rolle '{id}' existiert bereits mit anderen Berechtigungen.", "Esiste già un ruolo '{id}' con autorizzazioni diverse."],
  'update_scope_change': ["The new rules apply outside the assignable scopes of role '{id}'; clone the role or retire it and create a new one.", "Les nouvelles règles s'appliquent en dehors des périmètres attribuables du rôle « {id} » ; clonez le rôle ou retirez-le et créez-en un nouveau.", "Las nuevas reglas se aplican fuera de los ámbitos asignables del rol '{id}'; clone el rol o retírelo y cree uno nuevo.", "Die neuen Regeln gelten außerhalb der zuweisbaren Bereiche der Rolle '{id}'; klonen Sie die Rolle oder nehmen Sie sie außer Betrieb und erstellen Sie eine neue.", "Le nuove regole si applicano al di fuori degli ambiti assegnabili del ruolo '{id}'; clonare il ruolo oppure ritirarlo e crearne uno nuovo."],
  'invalid_name': ['Invalid role name: use 1 to {limit} characters.', 'Nom de rôle invalide : utilisez de 1 à {limit} caractères.', 'Nombre de rol no válido: use de 1 a {limit} caracteres.', 'Ungültiger Rollenname: Verwenden Sie 1 bis {limit} Zeichen.', 'Nome del ruolo non valido: usare da 1 a {limit} caratteri.'],
  'retire_in_use': ["Role '{id}' still has {count} assignment(s); remove them before retiring.", "Le rôle « {id} » a encore {count} attribution(s) ; supprimez-les avant de le retirer.", "El rol '{id}' aún tiene {count} asignación(es); quítelas antes de retirarlo.", "Die Rolle '{id}' hat noch {count} Zuweisung(en); entfernen Sie diese vor der Außerbetriebnahme.", "Il ruolo '{id}' ha ancora {count} assegnazione/i; rimuoverle prima del ritiro."],
  'restore_no_reference': ['The retirement certificate holds no rollback reference.', "Le certificat de retrait ne contient aucune référence de restauration.", 'El certificado de retiro no contiene ninguna referencia de restauración.', 'Das Außerbetriebnahme-Zertifikat enthält keine Rollback-Referenz.', 'Il certificato di ritiro non contiene alcun riferimento di ripristino.'],
  'restore_invalid_snapshot': ["The rollback snapshot does not match the role '{id}'.", "L'instantané de restauration ne correspond pas au rôle « {id} ».", "La instantánea de restauración no coincide con el rol '{id}'.", "Der Rollback-Snapshot passt nicht zur Rolle '{id}'.", "Lo snapshot di ripristino non corrisponde al ruolo '{id}'."],
  'conflict_explanation': ["A Deny rule for '{subject}' at '{denyScope}' overlaps an Allow rule at '{allowScope}'; Azure cannot enforce the Deny.", "Une règle Deny pour « {subject} » sur « {denyScope} » chevauche une règle Allow sur « {allowScope} » ; Azure ne peut pas appliquer le refus.", "Una regla Deny para '{subject}' en '{denyScope}' se solapa con una regla Allow en '{allowScope}'; Azure no puede aplicar la denegación.", "Eine Deny-Regel für '{subject}' auf '{denyScope}' überschneidet sich mit einer Allow-Regel auf '{allowScope}'; Azure kann die Verweigerung nicht durchsetzen.", "Una regola Deny per '{subject}' su '{denyScope}' si sovrappone a una regola Allow su '{allowScope}'; Azure non può applicare la negazione."],
  'validate.no_permissions': ['The role grants no permissions.', "Le rôle n'accorde aucune autorisation.", 'El rol no concede ningún permiso.', 'Die Rolle gewährt keine Berechtigungen.', 'Il ruolo non concede alcuna autorizzazione.'],
  'validate.invalid_role_name': ['The role name must be 1 to {limit} characters.', 'Le nom du rôle doit comporter de 1 à {limit} caractères.', 'El nombre del rol debe tener de 1 a {limit} caracteres.', 'Der Rollenname muss 1 bis {limit} Zeichen lang sein.', 'Il nome del ruolo deve contenere da 1 a {limit} caratteri.'],
  'validate.admin_wildcard': ['The role grants every operation (*), which violates least privilege.', 'Le rôle accorde toutes les opérations (*), ce qui viole le principe du moindre privilège.', 'El rol concede todas las operaciones (*), lo que infringe el mínimo privilegio.', 'Die Rolle gewährt alle Operationen (*) und verstößt damit gegen das Prinzip der minimalen Rechte.', 'Il ruolo concede tutte le operazioni (*), violando il principio del privilegio minimo.'],
  'validate.invalid_action': ["Invalid operation '{action}': expected <provider>/<resource>/<verb>.", "Opération invalide « {action} » : format attendu <fournisseur>/<ressource>/<verbe>.", "Operación no válida '{action}': se esperaba <proveedor>/<recurso>/<verbo>.", "Ungültige Operation '{action}': Erwartet wird <Anbieter>/<Ressource>/<Verb>.", "Operazione non valida '{action}': formato atteso <provider>/<risorsa>/<verbo>."],
  'validate.broad_wildcard': ["The operation '{action}' covers a whole family of operations; prefer explicit operations.", "L'opération « {action} » couvre toute une famille d'opérations ; privilégiez des opérations explicites.", "La operación '{action}' abarca toda una familia de operaciones; prefiera operaciones explícitas.", "Die Operation '{action}' deckt eine ganze Familie von Operationen ab; bevorzugen Sie explizite Operationen.", "L'operazione '{action}' copre un'intera famiglia di operazioni; preferire operazioni esplicite."],
  'validate.no_assignable_scopes': ['The role has no assignable scopes.', "Le rôle n'a aucun périmètre attribuable.", 'El rol no tiene ámbitos asignables.', 'Die Rolle hat keine zuweisbaren Bereiche.', 'Il ruolo non ha ambiti assegnabili.'],
  'validate.resource_assignable': ["The assignable scope '{scope}' is a single resource; use a resource group, subscription or management group.", "Le périmètre attribuable « {scope} » est une ressource unique ; utilisez un groupe de ressources, un abonnement ou un groupe d'administration.", "El ámbito asignable '{scope}' es un único recurso; use un grupo de recursos, una suscripción o un grupo de administración.", "Der zuweisbare Bereich '{scope}' ist eine einzelne Ressource; verwenden Sie eine Ressourcengruppe, ein Abonnement oder eine Verwaltungsgruppe.", "L'ambito assegnabile '{scope}' è una singola risorsa; usare un gruppo di risorse, una sottoscrizione o un gruppo di gestione."],
  'validate.assignment_outside': ["The assignment scope '{scope}' lies outside the role's assignable scopes.", "Le périmètre d'attribution « {scope} » est en dehors des périmètres attribuables du rôle.", "El ámbito de asignación '{scope}' queda fuera de los ámbitos asignables del rol.", "Der Zuweisungsbereich '{scope}' liegt außerhalb der zuweisbaren Bereiche der Rolle.", "L'ambito di assegnazione '{scope}' è al di fuori degli ambiti assegnabili del ruolo."],
  'validate.digest_mismatch': ['The role digest does not match its document.', 'Le condensat du rôle ne correspond pas à son document.', 'El resumen del rol no coincide con su documento.', 'Der Rollen-Digest stimmt nicht mit dem Dokument überein.', 'Il digest del ruolo non corrisponde al documento.'],
};
const setNested = (obj, dotted, value) => {
  const parts = dotted.split('.'); let o = obj;
  for (let i = 0; i < parts.length - 1; i++) { if (typeof o[parts[i]] !== 'object' || o[parts[i]] === null) o[parts[i]] = {}; o = o[parts[i]]; }
  o[parts[parts.length - 1]] = value;
};
LANGS.forEach((lang, idx) => {
  const p = path.join(dir, `${lang}.json`);
  const obj = JSON.parse(fs.readFileSync(p, 'utf8'));
  for (const [k, v] of Object.entries(cat)) setNested(obj, P + k, v[idx]);
  if (obj.azure && obj.azure.rbac) { delete obj.azure.rbac; if (Object.keys(obj.azure).length === 0) delete obj.azure; } // superseded by uppie.adapter.azure.*
  fs.writeFileSync(p, JSON.stringify(obj, null, 2) + '\n', 'utf8');
});
console.log('written', Object.keys(cat).length, 'keys x 5 locales (overwrite-capable)');
