// Locale catalogue for the provider capability contract (fabric.contract.*) and plan rejection; overwrite-capable and idempotent.
const fs = require('fs');
const path = require('path');
const dir = path.join(__dirname, '..', 'server', 'shared', 'locales');
const LANGS = ['en', 'fr', 'es', 'de', 'it'];
const cat = {
  // ---- registration errors
  'fabric.contract.provider_name_missing': ['A provider declaration must name its provider.', "Une déclaration de fournisseur doit nommer son fournisseur.", 'Una declaración de proveedor debe indicar el nombre del proveedor.', 'Eine Anbieterdeklaration muss den Anbieter benennen.', 'Una dichiarazione di provider deve indicare il nome del provider.'],
  'fabric.contract.kind_undeclared': ["Provider '{provider}' does not declare a capability for {kind}; every kind must be declared as NATIVE, CONDITIONAL or UNSUPPORTED.", "Le fournisseur « {provider} » ne déclare aucune capacité pour {kind} ; chaque type doit être déclaré NATIVE, CONDITIONAL ou UNSUPPORTED.", "El proveedor '{provider}' no declara ninguna capacidad para {kind}; cada tipo debe declararse NATIVE, CONDITIONAL o UNSUPPORTED.", "Der Anbieter '{provider}' deklariert keine Fähigkeit für {kind}; jede Art muss als NATIVE, CONDITIONAL oder UNSUPPORTED deklariert werden.", "Il provider '{provider}' non dichiara alcuna capacità per {kind}; ogni tipo deve essere dichiarato NATIVE, CONDITIONAL o UNSUPPORTED."],
  'fabric.contract.adapter_for_unsupported': ["Provider '{provider}' declares {kind} as UNSUPPORTED but supplies an adapter for it.", "Le fournisseur « {provider} » déclare {kind} comme UNSUPPORTED mais fournit un adaptateur pour ce type.", "El proveedor '{provider}' declara {kind} como UNSUPPORTED pero suministra un adaptador para él.", "Der Anbieter '{provider}' deklariert {kind} als UNSUPPORTED, liefert dafür aber einen Adapter.", "Il provider '{provider}' dichiara {kind} come UNSUPPORTED ma fornisce un adattatore per esso."],
  'fabric.contract.adapter_missing': ["Provider '{provider}' declares {kind} as supported but supplies no adapter for it.", "Le fournisseur « {provider} » déclare {kind} comme pris en charge mais ne fournit aucun adaptateur.", "El proveedor '{provider}' declara {kind} como admitido pero no suministra ningún adaptador.", "Der Anbieter '{provider}' deklariert {kind} als unterstützt, liefert aber keinen Adapter.", "Il provider '{provider}' dichiara {kind} come supportato ma non fornisce alcun adattatore."],
  'fabric.contract.conditional_without_modes': ["Provider '{provider}' declares {kind} as CONDITIONAL without naming the modes it supports.", "Le fournisseur « {provider} » déclare {kind} comme CONDITIONAL sans nommer les modes pris en charge.", "El proveedor '{provider}' declara {kind} como CONDITIONAL sin indicar los modos admitidos.", "Der Anbieter '{provider}' deklariert {kind} als CONDITIONAL, ohne die unterstützten Modi zu nennen.", "Il provider '{provider}' dichiara {kind} come CONDITIONAL senza indicare le modalità supportate."],
  'fabric.contract.provider_already_registered': ["Provider '{provider}' is already registered.", "Le fournisseur « {provider} » est déjà enregistré.", "El proveedor '{provider}' ya está registrado.", "Der Anbieter '{provider}' ist bereits registriert.", "Il provider '{provider}' è già registrato."],
  'fabric.contract.provider_not_registered': ["Provider '{provider}' is not registered; install and configure it before using it in a plan.", "Le fournisseur « {provider} » n'est pas enregistré ; installez-le et configurez-le avant de l'utiliser dans un plan.", "El proveedor '{provider}' no está registrado; instálelo y configúrelo antes de usarlo en un plan.", "Der Anbieter '{provider}' ist nicht registriert; installieren und konfigurieren Sie ihn, bevor Sie ihn in einem Plan verwenden.", "Il provider '{provider}' non è registrato; installalo e configuralo prima di usarlo in un piano."],
  'fabric.contract.capability_unsupported': ["Provider '{provider}' does not support {kind}.", "Le fournisseur « {provider} » ne prend pas en charge {kind}.", "El proveedor '{provider}' no admite {kind}.", "Der Anbieter '{provider}' unterstützt {kind} nicht.", "Il provider '{provider}' non supporta {kind}."],
  // ---- reasons
  'fabric.contract.reason.generic': ["Provider '{provider}' cannot faithfully implement {kind}.", "Le fournisseur « {provider} » ne peut pas implémenter fidèlement {kind}.", "El proveedor '{provider}' no puede implementar {kind} fielmente.", "Der Anbieter '{provider}' kann {kind} nicht originalgetreu umsetzen.", "Il provider '{provider}' non può implementare fedelmente {kind}."],
  'fabric.contract.reason.kubernetes_network': ['Kubernetes has no network boundary of its own; networking is supplied by the cluster. A bare CIDR block cannot be applied, only NetworkPolicy traffic rules are supported.', "Kubernetes n'a pas de frontière réseau propre ; le réseau est fourni par le cluster. Un simple bloc CIDR ne peut pas être appliqué, seules les règles de trafic NetworkPolicy sont prises en charge.", 'Kubernetes no tiene un límite de red propio; la red la proporciona el clúster. No se puede aplicar un bloque CIDR por sí solo, solo se admiten reglas de tráfico NetworkPolicy.', 'Kubernetes hat keine eigene Netzwerkgrenze; das Netzwerk stellt der Cluster bereit. Ein reiner CIDR-Block kann nicht angewendet werden, nur NetworkPolicy-Verkehrsregeln werden unterstützt.', "Kubernetes non ha un confine di rete proprio; la rete è fornita dal cluster. Un semplice blocco CIDR non può essere applicato, sono supportate solo le regole di traffico NetworkPolicy."],
  'fabric.contract.reason.kubernetes_database': ['Core Kubernetes has no managed database primitive; a database container is not equivalent to a managed database.', "Kubernetes de base n'a pas de primitive de base de données gérée ; un conteneur de base de données n'équivaut pas à une base de données gérée.", 'Kubernetes básico no tiene una primitiva de base de datos gestionada; un contenedor de base de datos no equivale a una base de datos gestionada.', 'Kubernetes selbst hat keine verwaltete Datenbankprimitive; ein Datenbank-Container ist keiner verwalteten Datenbank gleichwertig.', 'Kubernetes di base non ha una primitiva di database gestito; un container di database non equivale a un database gestito.'],
  'fabric.contract.reason.kubernetes_storage': ['Kubernetes serves FILE and BLOCK storage through persistent volume claims; it has no object storage.', "Kubernetes fournit le stockage FILE et BLOCK via des revendications de volume persistant ; il n'a pas de stockage objet.", 'Kubernetes ofrece almacenamiento FILE y BLOCK mediante reclamaciones de volumen persistente; no tiene almacenamiento de objetos.', 'Kubernetes stellt FILE- und BLOCK-Speicher über Persistent Volume Claims bereit; es gibt keinen Objektspeicher.', 'Kubernetes offre storage FILE e BLOCK tramite persistent volume claim; non ha storage a oggetti.'],
  'fabric.contract.reason.linux_network': ['A Linux host is configured only through a declared network backend (existing, NetworkManager, systemd-networkd or Netplan); Ugondu never reconfigures host networking unasked.', "Un hôte Linux n'est configuré que via un backend réseau déclaré (existant, NetworkManager, systemd-networkd ou Netplan) ; Ugondu ne reconfigure jamais le réseau d'un hôte sans demande.", 'Un host Linux solo se configura mediante un backend de red declarado (existente, NetworkManager, systemd-networkd o Netplan); Ugondu nunca reconfigura la red de un host sin que se pida.', 'Ein Linux-Host wird nur über ein deklariertes Netzwerk-Backend konfiguriert (vorhanden, NetworkManager, systemd-networkd oder Netplan); Ugondu ändert die Netzwerkkonfiguration eines Hosts nie ungefragt.', "Un host Linux viene configurato solo tramite un backend di rete dichiarato (esistente, NetworkManager, systemd-networkd o Netplan); Ugondu non riconfigura mai la rete di un host senza richiesta."],
  'fabric.contract.reason.linux_database': ['A plain Linux host has no managed database primitive; Ugondu does not install database servers on a host unasked.', "Un hôte Linux simple n'a pas de primitive de base de données gérée ; Ugondu n'installe pas de serveur de base de données sur un hôte sans demande.", 'Un host Linux simple no tiene una primitiva de base de datos gestionada; Ugondu no instala servidores de bases de datos en un host sin que se pida.', 'Ein einfacher Linux-Host hat keine verwaltete Datenbankprimitive; Ugondu installiert nie ungefragt Datenbankserver auf einem Host.', 'Un semplice host Linux non ha una primitiva di database gestito; Ugondu non installa server di database su un host senza richiesta.'],
  'fabric.contract.reason.cpanel_compute': ['cPanel hosts applications inside an account; it cannot provide general compute resources.', "cPanel héberge des applications dans un compte ; il ne peut pas fournir de ressources de calcul générales.", 'cPanel aloja aplicaciones dentro de una cuenta; no puede proporcionar recursos de cómputo generales.', 'cPanel hostet Anwendungen innerhalb eines Kontos; es kann keine allgemeinen Rechenressourcen bereitstellen.', 'cPanel ospita applicazioni all\'interno di un account; non può fornire risorse di calcolo generiche.'],
  'fabric.contract.reason.cpanel_network': ['A cPanel account has no network boundary that Ugondu can manage.', "Un compte cPanel n'a pas de frontière réseau que Ugondu puisse gérer.", 'Una cuenta cPanel no tiene un límite de red que Ugondu pueda gestionar.', 'Ein cPanel-Konto hat keine Netzwerkgrenze, die Ugondu verwalten kann.', 'Un account cPanel non ha un confine di rete che Ugondu possa gestire.'],
  'fabric.contract.reason.cpanel_database': ['cPanel supports MySQL databases only.', 'cPanel ne prend en charge que les bases de données MySQL.', 'cPanel solo admite bases de datos MySQL.', 'cPanel unterstützt nur MySQL-Datenbanken.', 'cPanel supporta solo database MySQL.'],
  'fabric.contract.reason.cpanel_storage': ['cPanel provides account file storage only; it has no object storage.', "cPanel ne fournit que le stockage de fichiers du compte ; il n'a pas de stockage objet.", 'cPanel solo ofrece almacenamiento de archivos de la cuenta; no tiene almacenamiento de objetos.', 'cPanel bietet nur Dateispeicher des Kontos; es gibt keinen Objektspeicher.', "cPanel offre solo l'archiviazione di file dell'account; non ha storage a oggetti."],
  // ---- alternatives
  'fabric.contract.alt.install_plugin': ['Install and activate a database operator plugin that declares this capability.', "Installez et activez un plugin d'opérateur de base de données qui déclare cette capacité.", 'Instale y active un plugin de operador de base de datos que declare esta capacidad.', 'Installieren und aktivieren Sie ein Datenbank-Operator-Plugin, das diese Fähigkeit deklariert.', 'Installa e attiva un plugin operatore di database che dichiari questa capacità.'],
  'fabric.contract.alt.target_managed_provider': ['Target a provider that offers a managed database service.', 'Ciblez un fournisseur qui propose un service de base de données géré.', 'Use un proveedor que ofrezca un servicio de base de datos gestionado.', 'Wählen Sie einen Anbieter mit verwaltetem Datenbankdienst.', 'Scegli un provider che offra un servizio di database gestito.'],
  'fabric.contract.alt.remove_resource': ['Remove this resource from the plan.', 'Retirez cette ressource du plan.', 'Elimine este recurso del plan.', 'Entfernen Sie diese Ressource aus dem Plan.', 'Rimuovi questa risorsa dal piano.'],
  'fabric.contract.alt.target_network_provider': ['Target a provider that offers a network boundary.', 'Ciblez un fournisseur qui offre une frontière réseau.', 'Use un proveedor que ofrezca un límite de red.', 'Wählen Sie einen Anbieter mit Netzwerkgrenze.', 'Scegli un provider che offra un confine di rete.'],
  'fabric.contract.alt.use_network_policy_mode': ["Set the node's provider mode to NETWORK_POLICY.", 'Définissez le mode fournisseur du nœud sur NETWORK_POLICY.', 'Establezca el modo de proveedor del nodo en NETWORK_POLICY.', 'Setzen Sie den Anbietermodus des Knotens auf NETWORK_POLICY.', 'Imposta la modalità provider del nodo su NETWORK_POLICY.'],
  'fabric.contract.alt.use_file_or_block_class': ['Use the FILE or BLOCK storage class.', 'Utilisez la classe de stockage FILE ou BLOCK.', 'Use la clase de almacenamiento FILE o BLOCK.', 'Verwenden Sie die Speicherklasse FILE oder BLOCK.', 'Usa la classe di storage FILE o BLOCK.'],
  'fabric.contract.alt.target_object_storage_provider': ['Target a provider that offers object storage.', 'Ciblez un fournisseur qui propose du stockage objet.', 'Use un proveedor que ofrezca almacenamiento de objetos.', 'Wählen Sie einen Anbieter mit Objektspeicher.', 'Scegli un provider che offra storage a oggetti.'],
  'fabric.contract.alt.declare_network_backend': ["Declare the network backend in the node's provider mode.", 'Déclarez le backend réseau dans le mode fournisseur du nœud.', 'Declare el backend de red en el modo de proveedor del nodo.', 'Deklarieren Sie das Netzwerk-Backend im Anbietermodus des Knotens.', 'Dichiara il backend di rete nella modalità provider del nodo.'],
  'fabric.contract.alt.use_hosted_app_mode': ["Set the node's provider mode to HOSTED_APP.", 'Définissez le mode fournisseur du nœud sur HOSTED_APP.', 'Establezca el modo de proveedor del nodo en HOSTED_APP.', 'Setzen Sie den Anbietermodus des Knotens auf HOSTED_APP.', 'Imposta la modalità provider del nodo su HOSTED_APP.'],
  'fabric.contract.alt.use_mysql_mode': ['Use the MySQL engine with the MYSQL provider mode.', 'Utilisez le moteur MySQL avec le mode fournisseur MYSQL.', 'Use el motor MySQL con el modo de proveedor MYSQL.', 'Verwenden Sie die MySQL-Engine mit dem Anbietermodus MYSQL.', 'Usa il motore MySQL con la modalità provider MYSQL.'],
  'fabric.contract.alt.use_file_class': ['Use the FILE storage class.', 'Utilisez la classe de stockage FILE.', 'Use la clase de almacenamiento FILE.', 'Verwenden Sie die Speicherklasse FILE.', 'Usa la classe di storage FILE.'],
  'fabric.contract.alt.target_compute_provider': ['Target a provider that offers compute capacity.', 'Ciblez un fournisseur qui offre de la capacité de calcul.', 'Use un proveedor que ofrezca capacidad de cómputo.', 'Wählen Sie einen Anbieter mit Rechenkapazität.', 'Scegli un provider che offra capacità di calcolo.'],
  'fabric.contract.alt.set_provider_mode': ['Set providerOptions.mode to one of the supported modes.', 'Définissez providerOptions.mode sur l\'un des modes pris en charge.', 'Establezca providerOptions.mode en uno de los modos admitidos.', 'Setzen Sie providerOptions.mode auf einen der unterstützten Modi.', 'Imposta providerOptions.mode su una delle modalità supportate.'],
  'fabric.contract.alt.use_supported_storage_class': ['Use one of the storage classes this provider supports.', 'Utilisez l\'une des classes de stockage prises en charge par ce fournisseur.', 'Use una de las clases de almacenamiento que admite este proveedor.', 'Verwenden Sie eine der von diesem Anbieter unterstützten Speicherklassen.', 'Usa una delle classi di storage supportate da questo provider.'],
  'fabric.contract.alt.use_supported_engine': ['Use one of the database engines this provider supports.', 'Utilisez l\'un des moteurs de base de données pris en charge par ce fournisseur.', 'Use uno de los motores de base de datos que admite este proveedor.', 'Verwenden Sie eine der von diesem Anbieter unterstützten Datenbank-Engines.', 'Usa uno dei motori di database supportati da questo provider.'],
  'fabric.contract.alt.make_storage_private': ['Set isPublic to false.', 'Définissez isPublic sur false.', 'Establezca isPublic en false.', 'Setzen Sie isPublic auf false.', 'Imposta isPublic su false.'],
  'fabric.contract.alt.allow_public_storage_policy': ['Ask a policy administrator to allow public storage.', 'Demandez à un administrateur de politique d\'autoriser le stockage public.', 'Pida a un administrador de políticas que permita el almacenamiento público.', 'Bitten Sie einen Richtlinienadministrator, öffentlichen Speicher zuzulassen.', 'Chiedi a un amministratore delle policy di consentire lo storage pubblico.'],
  'fabric.contract.alt.confirm_public_access': ['Set publicAccessConfirmed to true once you have reviewed the security implications.', 'Définissez publicAccessConfirmed sur true après avoir examiné les implications de sécurité.', 'Establezca publicAccessConfirmed en true tras revisar las implicaciones de seguridad.', 'Setzen Sie publicAccessConfirmed auf true, nachdem Sie die Sicherheitsfolgen geprüft haben.', 'Imposta publicAccessConfirmed su true dopo aver esaminato le implicazioni di sicurezza.'],
  // ---- rejections
  'fabric.contract.rejection.mode_required': ["Provider '{provider}' supports {kind} only in a declared mode; set providerOptions.mode to one of: {modes}.", "Le fournisseur « {provider} » ne prend en charge {kind} que dans un mode déclaré ; définissez providerOptions.mode parmi : {modes}.", "El proveedor '{provider}' solo admite {kind} en un modo declarado; establezca providerOptions.mode en uno de: {modes}.", "Der Anbieter '{provider}' unterstützt {kind} nur in einem deklarierten Modus; setzen Sie providerOptions.mode auf einen von: {modes}.", "Il provider '{provider}' supporta {kind} solo in una modalità dichiarata; imposta providerOptions.mode su una tra: {modes}."],
  'fabric.contract.rejection.mode_unsupported': ["Mode '{mode}' is not supported by provider '{provider}' for {kind}; supported: {modes}.", "Le mode « {mode} » n'est pas pris en charge par le fournisseur « {provider} » pour {kind} ; pris en charge : {modes}.", "El modo '{mode}' no está admitido por el proveedor '{provider}' para {kind}; admitidos: {modes}.", "Der Modus '{mode}' wird vom Anbieter '{provider}' für {kind} nicht unterstützt; unterstützt: {modes}.", "La modalità '{mode}' non è supportata dal provider '{provider}' per {kind}; supportate: {modes}."],
  'fabric.contract.rejection.storage_class_unsupported': ["Provider '{provider}' does not support the {storageClass} storage class; supported: {classes}.", "Le fournisseur « {provider} » ne prend pas en charge la classe de stockage {storageClass} ; prises en charge : {classes}.", "El proveedor '{provider}' no admite la clase de almacenamiento {storageClass}; admitidas: {classes}.", "Der Anbieter '{provider}' unterstützt die Speicherklasse {storageClass} nicht; unterstützt: {classes}.", "Il provider '{provider}' non supporta la classe di storage {storageClass}; supportate: {classes}."],
  'fabric.contract.rejection.database_engine_unsupported': ["Provider '{provider}' does not support the {engine} database engine; supported: {engines}.", "Le fournisseur « {provider} » ne prend pas en charge le moteur de base de données {engine} ; pris en charge : {engines}.", "El proveedor '{provider}' no admite el motor de base de datos {engine}; admitidos: {engines}.", "Der Anbieter '{provider}' unterstützt die Datenbank-Engine {engine} nicht; unterstützt: {engines}.", "Il provider '{provider}' non supporta il motore di database {engine}; supportati: {engines}."],
  'fabric.contract.rejection.public_storage_unsupported': ["Public access is not meaningful for {storageClass} storage on provider '{provider}'.", "L'accès public n'a pas de sens pour le stockage {storageClass} chez le fournisseur « {provider} ».", "El acceso público no tiene sentido para el almacenamiento {storageClass} en el proveedor '{provider}'.", "Öffentlicher Zugriff ist für {storageClass}-Speicher beim Anbieter '{provider}' nicht sinnvoll.", "L'accesso pubblico non ha senso per lo storage {storageClass} sul provider '{provider}'."],
  'fabric.contract.rejection.public_storage_prohibited': ["Storage '{node}' requests public access, which the current policy prohibits.", "Le stockage « {node} » demande un accès public, ce que la politique actuelle interdit.", "El almacenamiento '{node}' solicita acceso público, lo que la política actual prohíbe.", "Der Speicher '{node}' fordert öffentlichen Zugriff an, den die aktuelle Richtlinie untersagt.", "Lo storage '{node}' richiede l'accesso pubblico, che la policy corrente vieta."],
  'fabric.contract.rejection.public_storage_unconfirmed': ["PUBLIC STORAGE WARNING: storage '{node}' permits anonymous read access. Confirm that you understand the security implications.", "AVERTISSEMENT STOCKAGE PUBLIC : le stockage « {node} » autorise la lecture anonyme. Confirmez que vous comprenez les implications de sécurité.", "ADVERTENCIA DE ALMACENAMIENTO PÚBLICO: el almacenamiento '{node}' permite lectura anónima. Confirme que comprende las implicaciones de seguridad.", "WARNUNG ÖFFENTLICHER SPEICHER: Der Speicher '{node}' erlaubt anonymes Lesen. Bestätigen Sie, dass Sie die Sicherheitsfolgen verstehen.", "AVVISO STORAGE PUBBLICO: lo storage '{node}' consente la lettura anonima. Conferma di comprendere le implicazioni di sicurezza."],
  'fabric.engine.secret_in_plan': ["Node '{node}': field '{field}' must be a secret reference (secret:<name>), never a secret value.", "Nœud « {node} » : le champ « {field} » doit être une référence de secret (secret:<nom>), jamais une valeur secrète.", "Nodo '{node}': el campo '{field}' debe ser una referencia de secreto (secret:<nombre>), nunca un valor secreto.", "Knoten '{node}': Das Feld '{field}' muss eine Geheimnisreferenz (secret:<name>) sein, niemals ein Geheimniswert.", "Nodo '{node}': il campo '{field}' deve essere un riferimento a un segreto (secret:<nome>), mai un valore segreto."],
  'fabric.engine.plan_rejected': ['PLAN REJECTED: {count} resource(s) cannot be provisioned as requested. No changes were made.', 'PLAN REJETÉ : {count} ressource(s) ne peuvent pas être provisionnées comme demandé. Aucune modification n\'a été effectuée.', 'PLAN RECHAZADO: {count} recurso(s) no se pueden aprovisionar como se solicitó. No se realizó ningún cambio.', 'PLAN ABGELEHNT: {count} Ressource(n) können nicht wie angefordert bereitgestellt werden. Es wurden keine Änderungen vorgenommen.', 'PIANO RIFIUTATO: {count} risorsa/e non possono essere predisposte come richiesto. Nessuna modifica è stata effettuata.'],
};
const setNested = (obj, dotted, value) => {
  const parts = dotted.split('.'); let o = obj;
  for (let i = 0; i < parts.length - 1; i++) { if (typeof o[parts[i]] !== 'object' || o[parts[i]] === null) o[parts[i]] = {}; o = o[parts[i]]; }
  o[parts[parts.length - 1]] = value;
};
LANGS.forEach((lang, idx) => {
  const p = path.join(dir, `${lang}.json`);
  const obj = JSON.parse(fs.readFileSync(p, 'utf8'));
  for (const [k, v] of Object.entries(cat)) {
    if (v.length !== LANGS.length) throw new Error('bad arity for ' + k);
    setNested(obj, k, v[idx]);
  }
  fs.writeFileSync(p, JSON.stringify(obj, null, 2) + '\n', 'utf8');
});
console.log('written', Object.keys(cat).length, 'keys x 5 locales (overwrite-capable)');
