// Locale catalogue for the GCP IAM adapter (uppie.adapter.gcp.*); overwrite-capable and idempotent.
const fs = require('fs');
const path = require('path');
const dir = path.join(__dirname, '..', 'server', 'shared', 'locales');
const LANGS = ['en', 'fr', 'es', 'de', 'it'];
const P = 'uppie.adapter.gcp.';
const cat = {
  'sdk_unavailable': ['The Google Cloud client libraries could not be loaded: {error}', "Les bibliothèques clientes Google Cloud n'ont pas pu être chargées : {error}", 'No se pudieron cargar las bibliotecas cliente de Google Cloud: {error}', 'Die Google-Cloud-Clientbibliotheken konnten nicht geladen werden: {error}', 'Impossibile caricare le librerie client di Google Cloud: {error}'],
  'invalid_resource': ["Invalid resource '{resource}': expected projects/<id>, folders/<id> or organizations/<id>.", "Ressource invalide « {resource} » : format attendu projects/<id>, folders/<id> ou organizations/<id>.", "Recurso no válido '{resource}': se esperaba projects/<id>, folders/<id> u organizations/<id>.", "Ungültige Ressource '{resource}': Erwartet wird projects/<id>, folders/<id> oder organizations/<id>.", "Risorsa non valida '{resource}': formato atteso projects/<id>, folders/<id> o organizations/<id>."],
  'scope_outside_environment': ["Resource '{resource}' is outside the environment's project and its ancestors.", "La ressource « {resource} » est en dehors du projet de l'environnement et de ses ancêtres.", "El recurso '{resource}' queda fuera del proyecto del entorno y de sus ancestros.", "Die Ressource '{resource}' liegt außerhalb des Projekts der Umgebung und seiner übergeordneten Ressourcen.", "La risorsa '{resource}' è al di fuori del progetto dell'ambiente e dei suoi antenati."],
  'no_organization': ["Resource '{resource}' has no organization, so a custom role cannot be defined for it.", "La ressource « {resource} » n'a pas d'organisation : un rôle personnalisé ne peut pas être défini pour elle.", "El recurso '{resource}' no tiene organización, por lo que no se puede definir un rol personalizado para él.", "Die Ressource '{resource}' gehört zu keiner Organisation; eine benutzerdefinierte Rolle kann dafür nicht definiert werden.", "La risorsa '{resource}' non ha un'organizzazione, quindi non è possibile definire un ruolo personalizzato per essa."],
  'invalid_member': ["Invalid member '{member}': expected user:, serviceAccount:, group:, domain:, principal:// or principalSet://.", "Membre invalide « {member} » : format attendu user:, serviceAccount:, group:, domain:, principal:// ou principalSet://.", "Miembro no válido '{member}': se esperaba user:, serviceAccount:, group:, domain:, principal:// o principalSet://.", "Ungültiges Mitglied '{member}': Erwartet wird user:, serviceAccount:, group:, domain:, principal:// oder principalSet://.", "Membro non valido '{member}': formato atteso user:, serviceAccount:, group:, domain:, principal:// o principalSet://."],
  'condition_unsupported': ["Rule '{ruleId}' uses a condition or constraint that cannot be expressed as an IAM condition; only time bounds are supported.", "La règle « {ruleId} » utilise une condition ou une contrainte qui ne peut pas être exprimée comme condition IAM ; seules les bornes temporelles sont prises en charge.", "La regla '{ruleId}' usa una condición o restricción que no se puede expresar como condición de IAM; solo se admiten límites de tiempo.", "Die Regel '{ruleId}' verwendet eine Bedingung oder Einschränkung, die sich nicht als IAM-Bedingung ausdrücken lässt; nur Zeitgrenzen werden unterstützt.", "La regola '{ruleId}' usa una condizione o un vincolo che non può essere espresso come condizione IAM; sono supportati solo i limiti temporali."],
  'deny_unsupported': ["Rule '{ruleId}' is a Deny rule; GCP deny policies are a separate policy type that this adapter does not create.", "La règle « {ruleId} » est une règle Deny ; les stratégies de refus de GCP sont un type de stratégie distinct que cet adaptateur ne crée pas.", "La regla '{ruleId}' es una regla Deny; las políticas de denegación de GCP son un tipo de política distinto que este adaptador no crea.", "Die Regel '{ruleId}' ist eine Deny-Regel; GCP-Verweigerungsrichtlinien sind ein eigener Richtlinientyp, den dieser Adapter nicht erstellt.", "La regola '{ruleId}' è una regola Deny; le policy di negazione di GCP sono un tipo di policy distinto che questo adattatore non crea."],
  'invalid_rule': ["Rule '{ruleId}' lists no operations.", "La règle « {ruleId} » ne liste aucune opération.", "La regla '{ruleId}' no enumera ninguna operación.", "Die Regel '{ruleId}' enthält keine Operationen.", "La regola '{ruleId}' non elenca alcuna operazione."],
  'no_rules': ['At least one rule is required.', 'Au moins une règle est requise.', 'Se requiere al menos una regla.', 'Mindestens eine Regel ist erforderlich.', 'È richiesta almeno una regola.'],
  'mixed_scopes': ['The rules differ in resource or condition; a role cannot merge them without widening access. Generate one policy per resource and condition.', 'Les règles diffèrent par la ressource ou la condition ; un rôle ne peut pas les fusionner sans élargir les accès. Générez une stratégie par ressource et condition.', 'Las reglas difieren en recurso o condición; un rol no puede combinarlas sin ampliar el acceso. Genere una política por recurso y condición.', 'Die Regeln unterscheiden sich in Ressource oder Bedingung; eine Rolle kann sie nicht zusammenführen, ohne den Zugriff zu erweitern. Erzeugen Sie je Ressource und Bedingung eine Richtlinie.', 'Le regole differiscono per risorsa o condizione; un ruolo non può unirle senza ampliare l\'accesso. Generare una policy per ogni risorsa e condizione.'],
  'role_title': ['Ugondu role {digest}', 'Rôle Ugondu {digest}', 'Rol Ugondu {digest}', 'Ugondu-Rolle {digest}', 'Ruolo Ugondu {digest}'],
  'role_description': ['Managed by Ugondu (digest {digest}).', 'Géré par Ugondu (condensat {digest}).', 'Gestionado por Ugondu (resumen {digest}).', 'Verwaltet von Ugondu (Digest {digest}).', 'Gestito da Ugondu (digest {digest}).'],
  'condition_title': ['Ugondu time bound {digest}', 'Borne temporelle Ugondu {digest}', 'Límite de tiempo de Ugondu {digest}', 'Ugondu-Zeitgrenze {digest}', 'Limite temporale Ugondu {digest}'],
  'policy_full': ['The allow policy already holds the maximum of {limit} principals.', 'La stratégie d\'autorisation contient déjà le maximum de {limit} principaux.', 'La política de permiso ya contiene el máximo de {limit} entidades.', 'Die Zulassungsrichtlinie enthält bereits die maximale Anzahl von {limit} Prinzipalen.', 'La policy di autorizzazione contiene già il massimo di {limit} entità.'],
  'policy_conflict': ["The allow policy of '{resource}' kept changing concurrently; no change was written, retry later.", "La stratégie d'autorisation de « {resource} » n'a cessé d'être modifiée simultanément ; aucune modification n'a été écrite, réessayez plus tard.", "La política de permiso de '{resource}' siguió cambiando de forma concurrente; no se escribió ningún cambio, inténtelo de nuevo más tarde.", "Die Zulassungsrichtlinie von '{resource}' wurde fortlaufend gleichzeitig geändert; es wurde nichts geschrieben, versuchen Sie es später erneut.", "La policy di autorizzazione di '{resource}' è stata modificata continuamente in modo concorrente; nessuna modifica è stata scritta, riprovare più tardi."],
  'conflict_explanation': ["A Deny rule for '{subject}' at '{denyScope}' overlaps an Allow rule at '{allowScope}'; this adapter does not create GCP deny policies, so the Deny is not enforced.", "Une règle Deny pour « {subject} » sur « {denyScope} » chevauche une règle Allow sur « {allowScope} » ; cet adaptateur ne crée pas de stratégies de refus GCP, le refus n'est donc pas appliqué.", "Una regla Deny para '{subject}' en '{denyScope}' se solapa con una regla Allow en '{allowScope}'; este adaptador no crea políticas de denegación de GCP, por lo que la denegación no se aplica.", "Eine Deny-Regel für '{subject}' auf '{denyScope}' überschneidet sich mit einer Allow-Regel auf '{allowScope}'; dieser Adapter erstellt keine GCP-Verweigerungsrichtlinien, daher wird die Verweigerung nicht durchgesetzt.", "Una regola Deny per '{subject}' su '{denyScope}' si sovrappone a una regola Allow su '{allowScope}'; questo adattatore non crea policy di negazione GCP, quindi la negazione non viene applicata."],
  'validate.no_permissions': ['The role grants no permissions.', "Le rôle n'accorde aucune autorisation.", 'El rol no concede ningún permiso.', 'Die Rolle gewährt keine Berechtigungen.', 'Il ruolo non concede alcuna autorizzazione.'],
  'validate.invalid_role_name': ["Invalid role name '{name}'.", 'Nom de rôle invalide « {name} ».', "Nombre de rol no válido '{name}'.", "Ungültiger Rollenname '{name}'.", "Nome del ruolo non valido '{name}'."],
  'validate.text_too_long': ['The role title is limited to {title} characters and its description to {description}.', 'Le titre du rôle est limité à {title} caractères et sa description à {description}.', 'El título del rol está limitado a {title} caracteres y su descripción a {description}.', 'Der Rollentitel ist auf {title} Zeichen und die Beschreibung auf {description} begrenzt.', 'Il titolo del ruolo è limitato a {title} caratteri e la descrizione a {description}.'],
  'validate.too_many_permissions': ['The role has {count} permissions; the maximum is {limit}.', 'Le rôle compte {count} autorisations ; le maximum est {limit}.', 'El rol tiene {count} permisos; el máximo es {limit}.', 'Die Rolle hat {count} Berechtigungen; das Maximum beträgt {limit}.', 'Il ruolo ha {count} autorizzazioni; il massimo è {limit}.'],
  'validate.invalid_permission': ["Invalid permission '{permission}': expected <service>.<resource>.<verb>.", "Autorisation invalide « {permission} » : format attendu <service>.<ressource>.<verbe>.", "Permiso no válido '{permission}': se esperaba <servicio>.<recurso>.<verbo>.", "Ungültige Berechtigung '{permission}': Erwartet wird <Dienst>.<Ressource>.<Verb>.", "Autorizzazione non valida '{permission}': formato atteso <servizio>.<risorsa>.<verbo>."],
  'validate.escalating_permission': ["The permission '{permission}' lets its holder widen access; review it before granting.", "L'autorisation « {permission} » permet à son titulaire d'élargir les accès ; vérifiez-la avant de l'accorder.", "El permiso '{permission}' permite a su titular ampliar el acceso; revíselo antes de concederlo.", "Die Berechtigung '{permission}' erlaubt es ihrem Inhaber, den Zugriff auszuweiten; prüfen Sie sie vor der Vergabe.", "L'autorizzazione '{permission}' consente al titolare di ampliare l'accesso; verificarla prima di concederla."],
  'validate.expression_too_long': ['The condition expression is limited to {limit} characters.', "L'expression de condition est limitée à {limit} caractères.", 'La expresión de la condición está limitada a {limit} caracteres.', 'Der Bedingungsausdruck ist auf {limit} Zeichen begrenzt.', "L'espressione della condizione è limitata a {limit} caratteri."],
  'validate.digest_mismatch': ['The policy digest does not match its document.', 'Le condensat de la stratégie ne correspond pas à son document.', 'El resumen de la política no coincide con su documento.', 'Der Richtlinien-Digest stimmt nicht mit dem Dokument überein.', 'Il digest della policy non corrisponde al documento.'],
  'attach_error': ['Could not attach the policy: {error}', "Impossible d'attacher la stratégie : {error}", 'No se pudo adjuntar la política: {error}', 'Die Richtlinie konnte nicht angehängt werden: {error}', 'Impossibile collegare la policy: {error}'],
  'detach_error': ['Could not detach the policy: {error}', "Impossible de détacher la stratégie : {error}", 'No se pudo desvincular la política: {error}', 'Die Richtlinie konnte nicht getrennt werden: {error}', 'Impossibile scollegare la policy: {error}'],
  'update_error': ['Could not update the policy: {error}', 'Impossible de mettre à jour la stratégie : {error}', 'No se pudo actualizar la política: {error}', 'Die Richtlinie konnte nicht aktualisiert werden: {error}', 'Impossibile aggiornare la policy: {error}'],
  'clone_error': ['Could not clone the policy: {error}', 'Impossible de cloner la stratégie : {error}', 'No se pudo clonar la política: {error}', 'Die Richtlinie konnte nicht geklont werden: {error}', 'Impossibile clonare la policy: {error}'],
  'retire_error': ['Could not retire the policy: {error}', 'Impossible de retirer la stratégie : {error}', 'No se pudo retirar la política: {error}', 'Die Richtlinie konnte nicht außer Betrieb genommen werden: {error}', 'Impossibile ritirare la policy: {error}'],
  'restore_error': ['Could not restore the policy: {error}', 'Impossible de restaurer la stratégie : {error}', 'No se pudo restaurar la política: {error}', 'Die Richtlinie konnte nicht wiederhergestellt werden: {error}', 'Impossibile ripristinare la policy: {error}'],
  'reconcile_error': ['Could not reconcile the policies: {error}', 'Impossible de réconcilier les stratégies : {error}', 'No se pudieron reconciliar las políticas: {error}', 'Die Richtlinien konnten nicht abgeglichen werden: {error}', 'Impossibile riconciliare le policy: {error}'],
  'protected_role': ["Role '{name}' is predefined and cannot be changed or retired; clone it instead.", "Le rôle « {name} » est prédéfini et ne peut être ni modifié ni retiré ; clonez-le plutôt.", "El rol '{name}' es predefinido y no se puede modificar ni retirar; clónelo en su lugar.", "Die Rolle '{name}' ist vordefiniert und kann weder geändert noch außer Betrieb genommen werden; klonen Sie sie stattdessen.", "Il ruolo '{name}' è predefinito e non può essere modificato né ritirato; clonarlo invece."],
  'role_exists_different': ["A role '{name}' already exists with different permissions.", "Un rôle « {name} » existe déjà avec des autorisations différentes.", "Ya existe un rol '{name}' con permisos diferentes.", "Eine Rolle '{name}' existiert bereits mit anderen Berechtigungen.", "Esiste già un ruolo '{name}' con autorizzazioni diverse."],
  'update_condition_change': ["The new rules carry a condition, which belongs to a binding and cannot be stored in role '{name}'; generate and attach a new policy instead.", "Les nouvelles règles portent une condition, qui appartient à une liaison et ne peut pas être stockée dans le rôle « {name} » ; générez et attachez plutôt une nouvelle stratégie.", "Las nuevas reglas llevan una condición, que pertenece a un enlace y no se puede guardar en el rol '{name}'; genere y adjunte una nueva política.", "Die neuen Regeln enthalten eine Bedingung, die zu einer Bindung gehört und nicht in der Rolle '{name}' gespeichert werden kann; erzeugen und hängen Sie stattdessen eine neue Richtlinie an.", "Le nuove regole contengono una condizione, che appartiene a un'associazione e non può essere memorizzata nel ruolo '{name}'; generare e collegare invece una nuova policy."],
  'update_scope_change': ["The new rules apply to a resource whose custom role would be defined elsewhere than '{name}'; create a new policy instead.", "Les nouvelles règles s'appliquent à une ressource dont le rôle personnalisé serait défini ailleurs que « {name} » ; créez plutôt une nouvelle stratégie.", "Las nuevas reglas se aplican a un recurso cuyo rol personalizado se definiría en un lugar distinto de '{name}'; cree una nueva política.", "Die neuen Regeln gelten für eine Ressource, deren benutzerdefinierte Rolle anderswo als '{name}' definiert würde; erstellen Sie stattdessen eine neue Richtlinie.", "Le nuove regole si applicano a una risorsa il cui ruolo personalizzato sarebbe definito altrove rispetto a '{name}'; creare invece una nuova policy."],
  'invalid_name': ["Invalid role ID '{name}': use 3 to 64 letters, digits, underscores or periods.", "Identifiant de rôle invalide « {name} » : utilisez de 3 à 64 lettres, chiffres, traits de soulignement ou points.", "ID de rol no válido '{name}': use de 3 a 64 letras, dígitos, guiones bajos o puntos.", "Ungültige Rollen-ID '{name}': Verwenden Sie 3 bis 64 Buchstaben, Ziffern, Unterstriche oder Punkte.", "ID ruolo non valido '{name}': usare da 3 a 64 lettere, cifre, caratteri di sottolineatura o punti."],
  'retire_in_use': ["Role '{name}' is still referenced by {count} binding(s); remove them before retiring.", "Le rôle « {name} » est encore référencé par {count} liaison(s) ; supprimez-les avant de le retirer.", "El rol '{name}' aún está referenciado por {count} enlace(s); quítelos antes de retirarlo.", "Die Rolle '{name}' wird noch von {count} Bindung(en) referenziert; entfernen Sie diese vor der Außerbetriebnahme.", "Il ruolo '{name}' è ancora referenziato da {count} associazione/i; rimuoverle prima del ritiro."],
  'already_retired': ["Role '{name}' is already retired.", "Le rôle « {name} » est déjà retiré.", "El rol '{name}' ya está retirado.", "Die Rolle '{name}' ist bereits außer Betrieb genommen.", "Il ruolo '{name}' è già stato ritirato."],
  'shared_role': ["Role '{name}' is defined on the organization and shared with other projects; it cannot be changed, retired or restored from one environment.", "Le rôle « {name} » est défini au niveau de l'organisation et partagé avec d'autres projets ; il ne peut pas être modifié, retiré ni restauré depuis un seul environnement.", "El rol '{name}' está definido en la organización y compartido con otros proyectos; no se puede modificar, retirar ni restaurar desde un solo entorno.", "Die Rolle '{name}' ist auf Organisationsebene definiert und wird von anderen Projekten mitgenutzt; sie kann nicht aus einer einzelnen Umgebung geändert, außer Betrieb genommen oder wiederhergestellt werden.", "Il ruolo '{name}' è definito a livello di organizzazione e condiviso con altri progetti; non può essere modificato, ritirato o ripristinato da un solo ambiente."],
  'restore_no_reference': ['The retirement certificate holds no rollback reference.', 'Le certificat de retrait ne contient aucune référence de restauration.', 'El certificado de retiro no contiene ninguna referencia de restauración.', 'Das Außerbetriebnahme-Zertifikat enthält keine Rollback-Referenz.', 'Il certificato di ritiro non contiene alcun riferimento di ripristino.'],
  'restore_invalid_snapshot': ["The rollback snapshot does not match the role '{name}'.", "L'instantané de restauration ne correspond pas au rôle « {name} ».", "La instantánea de restauración no coincide con el rol '{name}'.", "Der Rollback-Snapshot passt nicht zur Rolle '{name}'.", "Lo snapshot di ripristino non corrisponde al ruolo '{name}'."],
};
const setNested = (obj, dotted, value) => {
  const parts = dotted.split('.'); let o = obj;
  for (let i = 0; i < parts.length - 1; i++) { if (typeof o[parts[i]] !== 'object' || o[parts[i]] === null) o[parts[i]] = {}; o = o[parts[i]]; }
  o[parts[parts.length - 1]] = value;
};
LANGS.forEach((lang, idx) => {
  const p = path.join(dir, `${lang}.json`);
  const obj = JSON.parse(fs.readFileSync(p, 'utf8'));
  for (const [k, v] of Object.entries(cat)) setNested(obj, P + k, v[idx]);
  if (obj.gcp && obj.gcp.iam) { delete obj.gcp.iam; if (Object.keys(obj.gcp).length === 0) delete obj.gcp; } // superseded by uppie.adapter.gcp.*
  fs.writeFileSync(p, JSON.stringify(obj, null, 2) + '\n', 'utf8');
});
console.log('written', Object.keys(cat).length, 'keys x 5 locales (overwrite-capable)');
