const fs = require('fs');
const path = require('path');
const dir = 'D:\\ujomor-platform\\products\\ugondu\\server\\shared\\locales';
const LANGS = ['en', 'fr', 'es', 'de', 'it'];
const P = 'uppie.adapter.k8s.';
const cat = {
  'attach_error': ['Failed to attach the policy: {error}', 'Échec du rattachement de la politique : {error}', 'Error al asociar la política: {error}', 'Die Richtlinie konnte nicht zugewiesen werden: {error}', 'Impossibile associare la policy: {error}'],
  'detach_error': ['Failed to detach the policy: {error}', 'Échec du détachement de la politique : {error}', 'Error al desasociar la política: {error}', 'Die Richtlinie konnte nicht entfernt werden: {error}', 'Impossibile dissociare la policy: {error}'],
  'update_error': ['Failed to update the policy: {error}', 'Échec de la mise à jour de la politique : {error}', 'Error al actualizar la política: {error}', 'Die Richtlinie konnte nicht aktualisiert werden: {error}', 'Impossibile aggiornare la policy: {error}'],
  'clone_error': ['Failed to clone the policy: {error}', 'Échec du clonage de la politique : {error}', 'Error al clonar la política: {error}', 'Die Richtlinie konnte nicht geklont werden: {error}', 'Impossibile clonare la policy: {error}'],
  'retire_error': ['Failed to retire the policy: {error}', 'Échec du retrait de la politique : {error}', 'Error al retirar la política: {error}', 'Die Richtlinie konnte nicht außer Betrieb genommen werden: {error}', 'Impossibile ritirare la policy: {error}'],
  'restore_error': ['Failed to restore the policy: {error}', 'Échec de la restauration de la politique : {error}', 'Error al restaurar la política: {error}', 'Die Richtlinie konnte nicht wiederhergestellt werden: {error}', 'Impossibile ripristinare la policy: {error}'],
  'reconcile_error': ['Failed to reconcile the policy: {error}', 'Échec du rapprochement de la politique : {error}', 'Error al conciliar la política: {error}', 'Die Richtlinie konnte nicht abgeglichen werden: {error}', 'Impossibile riconciliare la policy: {error}'],
  'sdk_unavailable': ['The Kubernetes client library is not available: {error}', "La bibliothèque cliente Kubernetes n'est pas disponible : {error}", 'La biblioteca cliente de Kubernetes no está disponible: {error}', 'Die Kubernetes-Clientbibliothek ist nicht verfügbar: {error}', 'La libreria client Kubernetes non è disponibile: {error}'],
  'invalid_rule': ["Invalid rule for '{scope}': at least one resource and one operation are required.", "Règle invalide pour « {scope} » : au moins une ressource et une opération sont requises.", "Regla no válida para '{scope}': se requieren al menos un recurso y una operación.", "Ungültige Regel für '{scope}': Mindestens eine Ressource und eine Operation sind erforderlich.", "Regola non valida per '{scope}': sono richiesti almeno una risorsa e un'operazione."],
  'invalid_scope': ["Invalid scope '{scope}': expected <resource>[.<apiGroup>][/<subresource>].", "Périmètre invalide « {scope} » : format attendu <ressource>[.<groupeApi>][/<sous-ressource>].", "Ámbito no válido '{scope}': se esperaba <recurso>[.<grupoApi>][/<subrecurso>].", "Ungültiger Geltungsbereich '{scope}': erwartet wird <Ressource>[.<API-Gruppe>][/<Unterressource>].", "Ambito non valido '{scope}': formato atteso <risorsa>[.<gruppoApi>][/<sottorisorsa>]."],
  'invalid_verb': ["Unsupported Kubernetes verb '{verb}'.", "Verbe Kubernetes non pris en charge « {verb} ».", "Verbo de Kubernetes no admitido '{verb}'.", "Nicht unterstütztes Kubernetes-Verb '{verb}'.", "Verbo Kubernetes non supportato '{verb}'."],
  'wildcard_forbidden': ["Wildcards are not permitted in generated policies: '{value}'.", "Les caractères génériques sont interdits dans les politiques générées : « {value} ».", "No se permiten comodines en las políticas generadas: '{value}'.", "Platzhalter sind in erzeugten Richtlinien nicht zulässig: '{value}'.", "I caratteri jolly non sono consentiti nelle policy generate: '{value}'."],
  'invalid_subject': ["Invalid subject '{subject}': use User:<name>, Group:<name> or ServiceAccount:<namespace>:<name>.", "Sujet invalide « {subject} » : utilisez User:<nom>, Group:<nom> ou ServiceAccount:<espace-de-noms>:<nom>.", "Sujeto no válido '{subject}': use User:<nombre>, Group:<nombre> o ServiceAccount:<espacio-de-nombres>:<nombre>.", "Ungültiges Subjekt '{subject}': Verwenden Sie User:<Name>, Group:<Name> oder ServiceAccount:<Namespace>:<Name>.", "Soggetto non valido '{subject}': usare User:<nome>, Group:<nome> o ServiceAccount:<namespace>:<nome>."],
  'protected_role': ["Role '{name}' is protected and cannot be modified, retired or restored.", "Le rôle « {name} » est protégé et ne peut être ni modifié, ni retiré, ni restauré.", "El rol '{name}' está protegido y no se puede modificar, retirar ni restaurar.", "Die Rolle '{name}' ist geschützt und kann weder geändert, außer Betrieb genommen noch wiederhergestellt werden.", "Il ruolo '{name}' è protetto e non può essere modificato, ritirato o ripristinato."],
  'retire_in_use': ["Role '{name}' is still referenced by {count} binding(s); detach it before retiring.", "Le rôle « {name} » est encore référencé par {count} liaison(s) ; détachez-le avant de le retirer.", "El rol '{name}' sigue referenciado por {count} enlace(s); desasócielo antes de retirarlo.", "Die Rolle '{name}' wird noch von {count} Bindung(en) referenziert; entfernen Sie diese vor der Außerbetriebnahme.", "Il ruolo '{name}' è ancora referenziato da {count} associazione/i; dissociarlo prima del ritiro."],
  'restore_invalid_snapshot': ["The rollback snapshot is not a valid ClusterRole named '{name}'.", "L'instantané de restauration n'est pas un ClusterRole valide nommé « {name} ».", "La instantánea de restauración no es un ClusterRole válido con el nombre '{name}'.", "Der Rollback-Snapshot ist keine gültige ClusterRole mit dem Namen '{name}'.", "Lo snapshot di ripristino non è un ClusterRole valido denominato '{name}'."],
  'role_exists_different': ["A role named '{name}' already exists with different rules.", "Un rôle nommé « {name} » existe déjà avec des règles différentes.", "Ya existe un rol llamado '{name}' con reglas diferentes.", "Eine Rolle mit dem Namen '{name}' existiert bereits mit anderen Regeln.", "Esiste già un ruolo denominato '{name}' con regole diverse."],
  'validate.invalid_name': ["Invalid ClusterRole name '{name}': it must be a DNS subdomain (lowercase alphanumerics, '-' and '.').", "Nom de ClusterRole invalide « {name} » : il doit être un sous-domaine DNS (minuscules, chiffres, « - » et « . »).", "Nombre de ClusterRole no válido '{name}': debe ser un subdominio DNS (minúsculas, dígitos, '-' y '.').", "Ungültiger ClusterRole-Name '{name}': Er muss eine DNS-Subdomain sein (Kleinbuchstaben, Ziffern, '-' und '.').", "Nome ClusterRole non valido '{name}': deve essere un sottodominio DNS (minuscole, cifre, '-' e '.')."],
  'validate.no_rules': ['The ClusterRole contains no rules.', 'Le ClusterRole ne contient aucune règle.', 'El ClusterRole no contiene ninguna regla.', 'Die ClusterRole enthält keine Regeln.', 'Il ClusterRole non contiene alcuna regola.'],
  'validate.too_large': ['The ClusterRole exceeds the {limit}-byte object size limit.', 'Le ClusterRole dépasse la limite de taille de {limit} octets.', 'El ClusterRole supera el límite de tamaño de {limit} bytes.', 'Die ClusterRole überschreitet das Größenlimit von {limit} Byte.', 'Il ClusterRole supera il limite di dimensione di {limit} byte.'],
  'validate.invalid_kind': ['The native document is not a ClusterRole.', "Le document natif n'est pas un ClusterRole.", 'El documento nativo no es un ClusterRole.', 'Das native Dokument ist keine ClusterRole.', 'Il documento nativo non è un ClusterRole.'],
  'validate.digest_mismatch': ['The policy digest does not match its document.', 'Le condensat de la politique ne correspond pas à son document.', 'El resumen de la política no coincide con su documento.', 'Der Richtlinien-Digest stimmt nicht mit dem Dokument überein.', 'Il digest della policy non corrisponde al documento.'],
};
const setNested = (obj, dotted, value) => {
  const parts = dotted.split('.'); let o = obj;
  for (let i = 0; i < parts.length - 1; i++) { if (typeof o[parts[i]] !== 'object' || o[parts[i]] === null) o[parts[i]] = {}; o = o[parts[i]]; }
  o[parts[parts.length - 1]] = value;
};
LANGS.forEach((lang, idx) => {
  const p = path.join(dir, `${lang}.json`);
  const obj = JSON.parse(fs.readFileSync(p, 'utf8'));
  for (const [k, v] of Object.entries(cat)) setNested(obj, P + k, v[idx]);
  fs.writeFileSync(p, JSON.stringify(obj, null, 2) + '\n', 'utf8');
});
console.log('written', Object.keys(cat).length, 'keys x 5 locales (overwrite-capable)');
