// Locale catalogue for the cPanel adapter (uppie.adapter.cpanel.*); overwrite-capable and idempotent.
const fs = require('fs');
const path = require('path');
const dir = path.join(__dirname, '..', 'server', 'shared', 'locales');
const LANGS = ['en', 'fr', 'es', 'de', 'it'];
const P = 'uppie.adapter.cpanel.';
const cat = {
  'invalid_host': ['The WHM host must be a plain host name or IPv4 address.', "L'hôte WHM doit être un nom d'hôte simple ou une adresse IPv4.", 'El host de WHM debe ser un nombre de host simple o una dirección IPv4.', 'Der WHM-Host muss ein einfacher Hostname oder eine IPv4-Adresse sein.', "L'host WHM deve essere un semplice nome host o un indirizzo IPv4."],
  'invalid_credentials': ['The WHM credentials are incomplete or malformed: username, API token and an optional port are required.', "Les identifiants WHM sont incomplets ou mal formés : nom d'utilisateur, jeton d'API et port facultatif requis.", 'Las credenciales de WHM están incompletas o mal formadas: se requieren nombre de usuario, token de API y, opcionalmente, puerto.', 'Die WHM-Zugangsdaten sind unvollständig oder fehlerhaft: Benutzername, API-Token und optional ein Port sind erforderlich.', 'Le credenziali WHM sono incomplete o malformate: sono richiesti nome utente, token API e, facoltativamente, la porta.'],
  'http_error': ["WHM call '{command}' failed with HTTP status {status}.", "L'appel WHM « {command} » a échoué avec le statut HTTP {status}.", "La llamada de WHM '{command}' falló con el estado HTTP {status}.", "Der WHM-Aufruf '{command}' ist mit HTTP-Status {status} fehlgeschlagen.", "La chiamata WHM '{command}' non è riuscita con stato HTTP {status}."],
  'invalid_response': ["WHM call '{command}' returned a response without metadata.", "L'appel WHM « {command} » a renvoyé une réponse sans métadonnées.", "La llamada de WHM '{command}' devolvió una respuesta sin metadatos.", "Der WHM-Aufruf '{command}' lieferte eine Antwort ohne Metadaten.", "La chiamata WHM '{command}' ha restituito una risposta senza metadati."],
  'api_error': ["WHM call '{command}' was refused: {reason}", "L'appel WHM « {command} » a été refusé : {reason}", "La llamada de WHM '{command}' fue rechazada: {reason}", "Der WHM-Aufruf '{command}' wurde abgelehnt: {reason}", "La chiamata WHM '{command}' è stata rifiutata: {reason}"],
  'timeout': ["WHM call '{command}' did not answer within {seconds} seconds.", "L'appel WHM « {command} » n'a pas répondu en {seconds} secondes.", "La llamada de WHM '{command}' no respondió en {seconds} segundos.", "Der WHM-Aufruf '{command}' wurde nicht innerhalb von {seconds} Sekunden beantwortet.", "La chiamata WHM '{command}' non ha risposto entro {seconds} secondi."],
  'network_error': ["WHM call '{command}' could not be completed: {error}", "L'appel WHM « {command} » n'a pas pu aboutir : {error}", "La llamada de WHM '{command}' no se pudo completar: {error}", "Der WHM-Aufruf '{command}' konnte nicht abgeschlossen werden: {error}", "La chiamata WHM '{command}' non è stato possibile completarla: {error}"],
  'unmanaged_list': ["Feature list '{name}' is not managed by Ugondu and is never changed or removed.", "La liste de fonctionnalités « {name} » n'est pas gérée par Ugondu et n'est jamais modifiée ni supprimée.", "La lista de funciones '{name}' no la gestiona Ugondu y nunca se modifica ni se elimina.", "Die Funktionsliste '{name}' wird nicht von Ugondu verwaltet und nie geändert oder entfernt.", "L'elenco di funzionalità '{name}' non è gestito da Ugondu e non viene mai modificato né rimosso."],
  'invalid_account': ["Invalid cPanel account name '{account}'.", "Nom de compte cPanel invalide « {account} ».", "Nombre de cuenta de cPanel no válido '{account}'.", "Ungültiger cPanel-Kontoname '{account}'.", "Nome account cPanel non valido '{account}'."],
  'account_not_found': ["No cPanel account named '{account}' exists on the server.", "Aucun compte cPanel nommé « {account} » n'existe sur le serveur.", "No existe ninguna cuenta de cPanel llamada '{account}' en el servidor.", "Auf dem Server existiert kein cPanel-Konto namens '{account}'.", "Sul server non esiste alcun account cPanel denominato '{account}'."],
  'invalid_name': ["Invalid feature list name '{name}': use up to 48 letters, digits, dots or hyphens.", "Nom de liste de fonctionnalités invalide « {name} » : utilisez jusqu'à 48 lettres, chiffres, points ou tirets.", "Nombre de lista de funciones no válido '{name}': use hasta 48 letras, dígitos, puntos o guiones.", "Ungültiger Name der Funktionsliste '{name}': bis zu 48 Buchstaben, Ziffern, Punkte oder Bindestriche verwenden.", "Nome dell'elenco di funzionalità non valido '{name}': usare fino a 48 lettere, cifre, punti o trattini."],
  'deny_unsupported': ["Rule '{ruleId}' is a Deny rule; cPanel has no Deny, so the rule is refused instead of being dropped.", "La règle « {ruleId} » est une règle Deny ; cPanel n'a pas de Deny, la règle est donc refusée plutôt qu'ignorée.", "La regla '{ruleId}' es una regla Deny; cPanel no tiene Deny, por lo que la regla se rechaza en lugar de omitirse.", "Die Regel '{ruleId}' ist eine Deny-Regel; cPanel kennt kein Deny, daher wird die Regel abgelehnt statt ausgelassen.", "La regola '{ruleId}' è una regola Deny; cPanel non ha Deny, quindi la regola viene rifiutata invece di essere ignorata."],
  'condition_unsupported': ["Rule '{ruleId}' uses a condition or constraint; cPanel feature lists cannot express conditions.", "La règle « {ruleId} » utilise une condition ou une contrainte ; les listes de fonctionnalités cPanel ne peuvent pas exprimer de conditions.", "La regla '{ruleId}' usa una condición o restricción; las listas de funciones de cPanel no pueden expresar condiciones.", "Die Regel '{ruleId}' verwendet eine Bedingung oder Einschränkung; cPanel-Funktionslisten können keine Bedingungen ausdrücken.", "La regola '{ruleId}' usa una condizione o un vincolo; gli elenchi di funzionalità cPanel non possono esprimere condizioni."],
  'validity_unsupported': ["Rule '{ruleId}' is time-limited; a cPanel feature list is permanent and cannot expire.", "La règle « {ruleId} » est limitée dans le temps ; une liste de fonctionnalités cPanel est permanente et ne peut pas expirer.", "La regla '{ruleId}' tiene límite de tiempo; una lista de funciones de cPanel es permanente y no puede caducar.", "Die Regel '{ruleId}' ist zeitlich begrenzt; eine cPanel-Funktionsliste ist dauerhaft und kann nicht ablaufen.", "La regola '{ruleId}' ha una durata limitata; un elenco di funzionalità cPanel è permanente e non può scadere."],
  'invalid_rule': ["Rule '{ruleId}' lists no operations.", "La règle « {ruleId} » ne liste aucune opération.", "La regla '{ruleId}' no enumera ninguna operación.", "Die Regel '{ruleId}' enthält keine Operationen.", "La regola '{ruleId}' non elenca alcuna operazione."],
  'no_rules': ['At least one rule is required.', 'Au moins une règle est requise.', 'Se requiere al menos una regla.', 'Mindestens eine Regel ist erforderlich.', 'È richiesta almeno una regola.'],
  'unknown_feature': ["'{feature}' is not a feature offered by this server.", "« {feature} » n'est pas une fonctionnalité proposée par ce serveur.", "'{feature}' no es una función que ofrezca este servidor.", "'{feature}' ist keine von diesem Server angebotene Funktion.", "'{feature}' non è una funzionalità offerta da questo server."],
  'catalog_unavailable': ["The feature list '{name}', which defines the features of the server, could not be found.", "La liste de fonctionnalités « {name} », qui définit les fonctionnalités du serveur, est introuvable.", "No se encontró la lista de funciones '{name}', que define las funciones del servidor.", "Die Funktionsliste '{name}', die die Funktionen des Servers festlegt, wurde nicht gefunden.", "L'elenco di funzionalità '{name}', che definisce le funzionalità del server, non è stato trovato."],
  'package_unresolved': ["The package '{plan}' of account '{account}' or its feature list could not be found.", "Le forfait « {plan} » du compte « {account} » ou sa liste de fonctionnalités est introuvable.", "No se encontró el paquete '{plan}' de la cuenta '{account}' o su lista de funciones.", "Das Paket '{plan}' des Kontos '{account}' oder seine Funktionsliste wurde nicht gefunden.", "Il pacchetto '{plan}' dell'account '{account}' o il suo elenco di funzionalità non è stato trovato."],
  'conflict_explanation': ["A Deny rule for '{subject}' overlaps an Allow rule on: {operations}. cPanel cannot express Deny, so the Deny is not enforced.", "Une règle Deny pour « {subject} » chevauche une règle Allow sur : {operations}. cPanel ne peut pas exprimer de Deny, le refus n'est donc pas appliqué.", "Una regla Deny para '{subject}' se solapa con una regla Allow en: {operations}. cPanel no puede expresar Deny, por lo que la denegación no se aplica.", "Eine Deny-Regel für '{subject}' überschneidet sich mit einer Allow-Regel bei: {operations}. cPanel kann kein Deny ausdrücken, daher wird die Verweigerung nicht durchgesetzt.", "Una regola Deny per '{subject}' si sovrappone a una regola Allow su: {operations}. cPanel non può esprimere Deny, quindi la negazione non viene applicata."],
  'list_exists_different': ["Feature list '{name}' already exists with different features and is left unchanged.", "La liste de fonctionnalités « {name} » existe déjà avec d'autres fonctionnalités et reste inchangée.", "La lista de funciones '{name}' ya existe con funciones distintas y se deja sin cambios.", "Die Funktionsliste '{name}' existiert bereits mit anderen Funktionen und bleibt unverändert.", "L'elenco di funzionalità '{name}' esiste già con funzionalità diverse e resta invariato."],
  'list_missing': ["Feature list '{name}' does not exist.", "La liste de fonctionnalités « {name} » n'existe pas.", "La lista de funciones '{name}' no existe.", "Die Funktionsliste '{name}' existiert nicht.", "L'elenco di funzionalità '{name}' non esiste."],
  'package_name_too_long': ["The package name '{name}' would exceed {max} characters; use a shorter original package.", "Le nom de forfait « {name} » dépasserait {max} caractères ; utilisez un forfait d'origine plus court.", "El nombre de paquete '{name}' superaría los {max} caracteres; use un paquete original más corto.", "Der Paketname '{name}' würde {max} Zeichen überschreiten; verwenden Sie ein kürzeres ursprüngliches Paket.", "Il nome del pacchetto '{name}' supererebbe {max} caratteri; usare un pacchetto originale più corto."],
  'origin_package_missing': ["The original package '{package}' of the account does not exist, so its settings cannot be kept or restored.", "Le forfait d'origine « {package} » du compte n'existe pas, ses paramètres ne peuvent donc être ni conservés ni restaurés.", "El paquete original '{package}' de la cuenta no existe, por lo que sus ajustes no se pueden conservar ni restaurar.", "Das ursprüngliche Paket '{package}' des Kontos existiert nicht; seine Einstellungen können weder beibehalten noch wiederhergestellt werden.", "Il pacchetto originale '{package}' dell'account non esiste, quindi le sue impostazioni non possono essere mantenute né ripristinate."],
  'package_conflict': ["Package '{name}' already exists with a different feature list and is left unchanged.", "Le forfait « {name} » existe déjà avec une autre liste de fonctionnalités et reste inchangé.", "El paquete '{name}' ya existe con otra lista de funciones y se deja sin cambios.", "Das Paket '{name}' existiert bereits mit einer anderen Funktionsliste und bleibt unverändert.", "Il pacchetto '{name}' esiste già con un altro elenco di funzionalità e resta invariato."],
  'retire_in_use': ["Feature list '{name}' is still used by {count} package(s) and cannot be retired.", "La liste de fonctionnalités « {name} » est encore utilisée par {count} forfait(s) et ne peut pas être retirée.", "La lista de funciones '{name}' aún la usan {count} paquete(s) y no se puede retirar.", "Die Funktionsliste '{name}' wird noch von {count} Paket(en) verwendet und kann nicht stillgelegt werden.", "L'elenco di funzionalità '{name}' è ancora usato da {count} pacchetto/i e non può essere ritirato."],
  'restore_no_reference': ['The retirement certificate holds no rollback snapshot.', "Le certificat de retrait ne contient aucun instantané de restauration.", 'El certificado de retirada no contiene ninguna instantánea de reversión.', 'Das Stilllegungszertifikat enthält keinen Wiederherstellungs-Snapshot.', 'Il certificato di ritiro non contiene alcuno snapshot di ripristino.'],
  'restore_invalid_snapshot': ["The rollback snapshot does not describe feature list '{name}'.", "L'instantané de restauration ne décrit pas la liste de fonctionnalités « {name} ».", "La instantánea de reversión no describe la lista de funciones '{name}'.", "Der Wiederherstellungs-Snapshot beschreibt nicht die Funktionsliste '{name}'.", "Lo snapshot di ripristino non descrive l'elenco di funzionalità '{name}'."],
  'validate.invalid_document': ['The policy document is missing or malformed.', 'Le document de stratégie est absent ou mal formé.', 'El documento de política falta o está mal formado.', 'Das Richtliniendokument fehlt oder ist fehlerhaft.', 'Il documento della policy è mancante o malformato.'],
  'validate.invalid_name': ["Invalid managed feature list name '{name}'.", "Nom de liste de fonctionnalités gérée invalide « {name} ».", "Nombre de lista de funciones gestionada no válido '{name}'.", "Ungültiger Name der verwalteten Funktionsliste '{name}'.", "Nome dell'elenco di funzionalità gestito non valido '{name}'."],
  'validate.no_features': ['The feature list enables no features.', "La liste de fonctionnalités n'active aucune fonctionnalité.", 'La lista de funciones no habilita ninguna función.', 'Die Funktionsliste aktiviert keine Funktionen.', "L'elenco di funzionalità non abilita alcuna funzionalità."],
  'validate.unknown_feature': ["'{feature}' is not a feature offered by this server.", "« {feature} » n'est pas une fonctionnalité proposée par ce serveur.", "'{feature}' no es una función que ofrezca este servidor.", "'{feature}' ist keine von diesem Server angebotene Funktion.", "'{feature}' non è una funzionalità offerta da questo server."],
  'validate.all_features': ['The feature list enables every feature of the server; review it before granting.', 'La liste de fonctionnalités active toutes les fonctionnalités du serveur ; vérifiez-la avant de l\'accorder.', 'La lista de funciones habilita todas las funciones del servidor; revísela antes de concederla.', 'Die Funktionsliste aktiviert alle Funktionen des Servers; prüfen Sie sie vor der Vergabe.', "L'elenco di funzionalità abilita tutte le funzionalità del server; verificarlo prima di concederlo."],
  'validate.digest_mismatch': ['The policy digest does not match its document.', 'Le condensat de la stratégie ne correspond pas à son document.', 'El resumen de la política no coincide con su documento.', 'Der Richtlinien-Digest stimmt nicht mit dem Dokument überein.', 'Il digest della policy non corrisponde al suo documento.'],
};
const failures = {
  attach_error: ['Attaching the feature list failed: {error}', "Le rattachement de la liste de fonctionnalités a échoué : {error}", 'Falló la asociación de la lista de funciones: {error}', 'Das Zuweisen der Funktionsliste ist fehlgeschlagen: {error}', "Il collegamento dell'elenco di funzionalità non è riuscito: {error}"],
  detach_error: ['Detaching the feature list failed: {error}', 'Le détachement de la liste de fonctionnalités a échoué : {error}', 'Falló la desasociación de la lista de funciones: {error}', 'Das Entfernen der Funktionsliste ist fehlgeschlagen: {error}', "Lo scollegamento dell'elenco di funzionalità non è riuscito: {error}"],
  update_error: ['Updating the feature list failed: {error}', 'La mise à jour de la liste de fonctionnalités a échoué : {error}', 'Falló la actualización de la lista de funciones: {error}', 'Das Aktualisieren der Funktionsliste ist fehlgeschlagen: {error}', "L'aggiornamento dell'elenco di funzionalità non è riuscito: {error}"],
  clone_error: ['Cloning the feature list failed: {error}', 'Le clonage de la liste de fonctionnalités a échoué : {error}', 'Falló la clonación de la lista de funciones: {error}', 'Das Klonen der Funktionsliste ist fehlgeschlagen: {error}', "La clonazione dell'elenco di funzionalità non è riuscita: {error}"],
  retire_error: ['Retiring the feature list failed: {error}', 'Le retrait de la liste de fonctionnalités a échoué : {error}', 'Falló la retirada de la lista de funciones: {error}', 'Das Stilllegen der Funktionsliste ist fehlgeschlagen: {error}', "Il ritiro dell'elenco di funzionalità non è riuscito: {error}"],
  restore_error: ['Restoring the feature list failed: {error}', 'La restauration de la liste de fonctionnalités a échoué : {error}', 'Falló la restauración de la lista de funciones: {error}', 'Das Wiederherstellen der Funktionsliste ist fehlgeschlagen: {error}', "Il ripristino dell'elenco di funzionalità non è riuscito: {error}"],
  reconcile_error: ['Reconciling the feature lists failed: {error}', 'Le rapprochement des listes de fonctionnalités a échoué : {error}', 'Falló la conciliación de las listas de funciones: {error}', 'Der Abgleich der Funktionslisten ist fehlgeschlagen: {error}', "La riconciliazione degli elenchi di funzionalità non è riuscita: {error}"],
};
Object.assign(cat, failures);
const OLD = ['attach', 'detach', 'update', 'clone', 'retire', 'restore']; // superseded cpanel.<op>.* keys
const setNested = (obj, dotted, value) => {
  const parts = dotted.split('.'); let o = obj;
  for (let i = 0; i < parts.length - 1; i++) { if (typeof o[parts[i]] !== 'object' || o[parts[i]] === null) o[parts[i]] = {}; o = o[parts[i]]; }
  o[parts[parts.length - 1]] = value;
};
LANGS.forEach((lang, idx) => {
  const p = path.join(dir, `${lang}.json`);
  const obj = JSON.parse(fs.readFileSync(p, 'utf8'));
  for (const [k, v] of Object.entries(cat)) setNested(obj, P + k, v[idx]);
  if (obj.cpanel) { for (const op of OLD) delete obj.cpanel[op]; if (Object.keys(obj.cpanel).length === 0) delete obj.cpanel; }
  fs.writeFileSync(p, JSON.stringify(obj, null, 2) + '\n', 'utf8');
});
console.log('written', Object.keys(cat).length, 'keys x 5 locales (overwrite-capable)');
