// Mutation check for the cPanel adapter: each mutant must be caught by at least one failing test.
const fs = require('fs');
const { execSync } = require('child_process');
const root = 'D:\\ujomor-platform\\products\\ugondu\\';
const A = 'server\\uppie\\src\\adapters\\cpanel\\';
const H = A + 'CpanelHelpers.ts', M = A + 'CpanelModel.ts', AD = A + 'CpanelAdapter.ts', W = A + 'WhmHttpClient.ts', C = A + 'CpanelConstraints.ts';
const mutations = [
  [H, "if (rule.effect !== 'ALLOW') throw fail", 'if (false) throw fail'],
  [H, 'rule.conditions.length > 0 ||', 'false ||'],
  [H, 'c.maxCallsPerHour !== undefined ||', 'false ||'],
  [H, '!!c.ipRange ||', 'false ||'],
  [H, '|| !!c.requireMfa) throw', '|| false) throw'],
  [H, "if (rule.validity.expiresAt !== 'PERMANENT') throw", 'if (false) throw'],
  [H, 'if (rule.action.operations.length === 0) throw', 'if (false) throw'],
  [H, 'if (rules.length === 0) throw', 'if (false) throw'],
  [H, 'features.add(op.trim())', 'features.add(op)'],
  [H, 'return [...features].sort();', 'return [...features];'],
  [H, 'if (!FEATURE_ID.test(feature) || !catalog.includes(feature)) throw fail', 'if (!FEATURE_ID.test(feature)) throw fail'],
  [H, 'digestOfFeatures(features).slice(0, 12)', 'digestOfFeatures(features).slice(0, 11)'],
  [H, 'if (document.features.length === 0) errors.push', 'if (false) errors.push'],
  [H, 'if (!isManagedList(document.name)) errors.push', 'if (false) errors.push'],
  [H, 'catalog.every((f) => document.features.includes(f))', 'false'],
  [H, 'const MANAGED_LIST = /^ugondu_[A-Za-z0-9.-]{1,48}$/;', 'const MANAGED_LIST = /^ugondu_[A-Za-z0-9._-]{1,48}$/;'],
  [H, 'if (!ACCOUNT_USER.test(user)) throw', 'if (false) throw'],
  [H, 'raw.startsWith(LIST_PREFIX) ? raw.slice(LIST_PREFIX.length) : raw', 'raw'],
  [H, 'if (!NAME_SUFFIX.test(suffix)) throw', 'if (false) throw'],
  [H, 'origin: match[2] as string', 'origin: match[1] as string'],
  [H, "export const PACKAGE_SEPARATOR = '__';", "export const PACKAGE_SEPARATOR = '_';"],
  [H, 'if (!base) throw fail', 'if (false) throw fail'],
  [H, 'if (!account) throw fail', 'if (false) throw fail'],
  [H, '(await client.listPackages()).filter((p) => p.featureList === list)', '(await client.listPackages())'],
  [H, 'names.has(a.plan)', 'true'],
  [H, 'pkg.featureList === list && !used.has(pkg.name)', 'pkg.featureList === list'],
  [H, 'pkg.featureList === list && !used.has(pkg.name)', '!used.has(pkg.name)'],
  [H, 'pkg.name.startsWith(`${list}${PACKAGE_SEPARATOR}`) && pkg.featureList === list', 'pkg.featureList === list'],
  [H, '(p) => p.name === account.plan', '(p) => p.name !== account.plan'],
  [M, "account.suspended ? { list: '', enabled: [] as string[] } : await featuresOfAccount(client, account)", 'await featuresOfAccount(client, account)'],
  [M, "if (!held) throw fail('uppie.adapter.cpanel.package_unresolved'", "if (false) throw fail('uppie.adapter.cpanel.package_unresolved'"],
  [M, "if (account.suspended) return 'DENIED';", "if (false) return 'DENIED';"],
  [M, 'return ops.every((op) =>', 'return ops.some((op) =>'],
  [M, "if (ops.length === 0) return 'UNKNOWN';", "if (false) return 'UNKNOWN';"],
  [M, "decided === 0 ? 'LOW' : skipped === 0 ? 'HIGH' : 'MEDIUM'", "'HIGH'"],
  [M, '(held.enabled.includes(f) ? unchanged : allowed)', '(held.enabled.includes(f) ? allowed : unchanged)'],
  [M, 'held.enabled.filter((x) => !features.includes(x))', 'held.enabled.filter((x) => features.includes(x))'],
  [M, 'classifyBlast(users.size, false)', 'classifyBlast(0, false)'],
  [M, 'classifyBlast(accounts.length, false)', 'classifyBlast(0, false)'],
  [M, 'skipped += features.length;', 'skipped += 0;'],
  [M, 'dependentActors: accounts.map((a) => a.user).sort()', 'dependentActors: accounts.map((a) => a.user)'],
  [M, 'dependentRoles: packages.map((p) => p.name).sort()', 'dependentRoles: packages.map((p) => p.name)'],
  [M, 'r.subject.id === deny.subject.id', 'true'],
  [M, "r.effect === 'ALLOW' && r.subject.id === deny.subject.id", 'r.subject.id === deny.subject.id'],
  [M, 'if (shared.length > 0)', 'if (true)'],
  [M, "shared.sort().join(', ')", "shared.join(', ')"],
  [M, 'if (!isManagedList(doc.name)) continue;', ''],
  [M, 'else if (sameSet([...current], [...features])) plan.noChange.push(id)', 'else if (true) plan.noChange.push(id)'],
  [M, 'plan.toRemove = [...have.keys()].filter((id) => !want.has(id));', 'plan.toRemove = [];'],
  [M, 'const id = `Allow|${parseUser(rule.subject.id)}`;', 'const id = `Allow|${rule.subject.id}`;'],
  [M, "resellers.has(a.user) ? 'WHM_RESELLER' : 'CPANEL_ACCOUNT'", "'CPANEL_ACCOUNT'"],
  [M, 'if (!byId.has(r)) byId.set(', 'byId.set('],
  [M, 'if (list) out[account.user] = [list];', 'out[account.user] = [list as string];'],
  [M, 'for (const name of (await client.listFeatureLists()).sort())', 'for (const name of (await client.listFeatureLists()))'],
  [M, 'return [...byId.values()].sort((a, b) => a.id.localeCompare(b.id));', 'return [...byId.values()];'],
  [M, 'policies: [p.featureList] })).sort((a, b) => a.id.localeCompare(b.id));', 'policies: [p.featureList] }));'],
  [AD, 'if (current?.list === document.name) return done;', 'if (false) return done;'],
  [AD, 'const origin = current ? current.origin : account.plan;', 'const origin = account.plan;'],
  [AD, 'if (name.length > MAX_PACKAGE_NAME) throw', 'if (false) throw'],
  [AD, 'if (!source) throw fail(', 'if (false) throw fail('],
  [AD, 'if (existing && existing.featureList !== document.name) throw', 'if (false) throw'],
  [AD, 'if (!list) await client.saveFeatureList(', 'if (true) await client.saveFeatureList('],
  [AD, 'if (!existing) await client.createPackage(', 'if (true) await client.createPackage('],
  [AD, 'attributes: source.attributes', 'attributes: {}'],
  [AD, 'if (current) await sweepOrphans(client, current.list);', ''],
  [AD, 'if (current?.list === policyId) {', 'if (true) {'],
  [AD, 'if (!(await client.listPackages()).some((p) => p.name === current.origin)) throw', 'if (false) throw'],
  [AD, 'await sweepOrphans(client, policyId);', ''],
  [AD, 'assertManaged(policyId);', ''],
  [AD, 'if (!(await client.getFeatureList(policyId))) throw', 'if (false) throw'],
  [AD, '      assertKnownFeatures(features, catalog);', ''],
  [AD, 'featureMap(catalog, features), true)', 'featureMap(catalog, features), false)'],
  [AD, "if (!source) throw fail('uppie.adapter.cpanel.list_missing'", "if (false) throw fail('uppie.adapter.cpanel.list_missing'"],
  [AD, 'if (!sameSet(enabledOf(existing.features), enabledOf(source.features))) throw', 'if (false) throw'],
  [AD, 'return usage(policyId, accounts.length, packages.length === 0);', 'return usage(policyId, accounts.length, true);'],
  [AD, 'usage(policyId, accounts.length, packages.length === 0)', 'usage(policyId, 0, packages.length === 0)'],
  [AD, 'if (!(await client.getFeatureList(policyId))) return usage(policyId, 0, false);', ''],
  [AD, '.filter((n) => isManagedList(n) && !used.has(n)).sort().map(', '.filter((n) => !used.has(n)).sort().map('],
  [AD, '.sort().map((n) => usage(n, 0, true))', '.map((n) => usage(n, 0, true))'],
  [AD, 'assertManaged(plan.policyId);', ''],
  [AD, 'if (packages.length > 0) throw', 'if (false) throw'],
  [AD, 'snapshot.name !== certificate.policyId ||', 'false ||'],
  [AD, '!Array.isArray(snapshot.features)) throw', 'false) throw'],
  [AD, '      assertManaged(snapshot.name);', ''],
  [AD, "if (errors.length > 0) throw new Error(errors.join('; '));", ''],
  [AD, 'if (!certificate.rollbackReference) return', 'if (false) return'],
  [AD, "throw fail('uppie.adapter.cpanel.reconcile_error', { error: errorText(e) });", 'throw e;'],
  [AD, "      return 'UNKNOWN';", "      return 'DENIED';"],
  [AD, 'this.clients.delete(key); throw e;', 'throw e;'],
  [AD, '[context.tenantId, context.environmentId, host, port, username]', '[context.tenantId, context.environmentId]'],
  [AD, 'nativePolicy.digest !== digestOfDocument(document)', 'false'],
  [AD, 'document && nativePolicy.digest && nativePolicy.digest !== digestOfDocument(document)', 'document && nativePolicy.digest !== digestOfDocument(document)'],
  [AD, 'if (existing && !sameSet(enabledOf(existing.features), document.features)) throw', 'if (false) throw'],
  [W, 'if (!HOST.test(host)) throw', 'if (false) throw'],
  [W, '!WHM_USER.test(username) ||', 'false ||'],
  [W, '!TOKEN.test(apiToken) ||', 'false ||'],
  [W, '!Number.isInteger(portNumber) ||', 'false ||'],
  [W, 'portNumber < 1 ||', 'false ||'],
  [W, '|| portNumber > 65535', '|| false'],
  [W, 'if (!response.ok) throw', 'if (false) throw'],
  [W, 'if (metadata.result === undefined) throw', 'if (false) throw'],
  [W, 'if (Number(metadata.result) !== 1) throw', 'if (false) throw'],
  [W, 'if (e instanceof WhmApiError) throw e;', ''],
  [W, 'if (controller.signal.aborted) throw', 'if (false) throw'],
  [W, "{ ...params, 'api.version': '1' }", "{ 'api.version': '1', ...params }"],
  [W, "overwrite ? 'update_featurelist' : 'create_featurelist'", "overwrite ? 'create_featurelist' : 'update_featurelist'"],
  [W, '{ ...params, featurelist: name }', '{ featurelist: name, ...params }'],
  [W, 'if (!(await listFeatureLists()).includes(name)) return undefined;', ''],
  [W, '{ ...params, name: pkg.name, featurelist: pkg.featureList }', '{ name: pkg.name, featurelist: pkg.featureList, ...params }'],
  [W, "{ lang: 'language' };", '{};'],
  [W, '&& !flag(f.is_disabled)', ''],
  [W, "!k.startsWith('_')", 'true'],
  [W, '.find((a) => a.user === user)', '.find(() => true)'],
  [W, "searchmethod: 'exact'", "searchmethod: 'regex'"],
  [W, 'suspended: flag(row.suspended)', 'suspended: false'],
  [W, "new Set(['name', 'featurelist', 'pkg', 'pkgname'])", 'new Set([])'],
  [W, 'Authorization: `whm ${username}:${apiToken}`', 'Authorization: `whm ${apiToken}`'],
  [C, 'value: featureCount,', 'value: 0,'],
];
let survived = 0;
for (const [file, from, to] of mutations) {
  const p = root + file;
  const original = fs.readFileSync(p, 'utf8');
  if (!original.includes(from)) { console.log('ANCHOR MISSING', file, from); continue; }
  fs.writeFileSync(p, original.replace(from, to));
  let out = '';
  try { out = execSync('node scratch\\run_qualification_gates.js', { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }); } catch (e) { out = String(e.stdout || ''); }
  fs.writeFileSync(p, original);
  const line = out.split(/\r?\n/).find((l) => l.includes('QUALIFICATION RESULTS')) || 'NO RESULT';
  const caught = !/\(0 failed\)/.test(line);
  if (!caught) survived++;
  console.log((caught ? 'caught   ' : 'SURVIVED ') + from.slice(0, 70).padEnd(72) + '=> ' + line.replace('QUALIFICATION RESULTS: ', ''));
}
console.log('survivors:', survived, 'of', mutations.length);
