// Mutation check for the provisioning engine and provider contract: each mutant must be caught by at least one failing test.
const fs = require('fs');
const { execSync } = require('child_process');
const root = 'D:\\ujomor-platform\\products\\ugondu\\';
const F = 'server\\engine-core\\src\\fabric\\';
const E = F + 'provisioning-engine.ts', H = F + 'engine\\NodeHandlers.ts', G = F + 'engine\\PlanGraph.ts', R = F + 'registry.ts', T = F + 'engine\\ProvisioningTypes.ts';
const P = F + 'engine\\Preflight.ts', S = F + 'engine\\SecretGuard.ts', CE = F + 'contract\\CapabilityEvaluation.ts', CC = F + 'contract\\CanonicalContracts.ts', PC = F + 'contract\\ProviderContract.ts', D = F + 'capabilities\\database.ts';
const mutations = [
  // ---- plan graph
  [G, "|| ids.has(node.id)) throw", '|| false) throw'],
  [G, "node.id === '' ||", 'false ||'],
  [G, 'if (!ids.has(end)) throw', 'if (false) throw'],
  [G, "(remaining.get(edge.to) as number) + 1", '(remaining.get(edge.to) as number) + 0'],
  [G, 'if (left === 0) ready.add(edge.to);', 'if (true) ready.add(edge.to);'],
  [G, 'if (placed !== ir.nodes.length) throw', 'if (false) throw'],
  [G, 'frontier = ir.nodes.filter((n) => ready.has(n.id));', 'frontier = ir.nodes.filter((n) => ready.has(n.id)).reverse();'],
  [G, 'if (edge.from !== node.id) continue;', 'if (false) continue;'],
  [G, '        queue.push(edge.from);', ''],
  [G, "typeof v === 'string' && v.startsWith(REF_PREFIX)).map", "typeof v === 'string').map"],
  [G, '.map((v) => v.slice(REF_PREFIX.length))', '.map((v) => v)'],
  [G, 'if (resourceId === undefined) throw', 'if (false) throw'],
  [G, 'Object.keys(value as object).sort()', 'Object.keys(value as object)'],
  [G, 'Array.isArray(value) ? value.map(canonical)', 'Array.isArray(value) ? value'],
  [G, 'canonical({ kind, provider, config, options })', 'canonical({ kind, config, options })'],
  [G, 'canonical({ kind, provider, config, options })', 'canonical({ kind, provider, config })'],
  [G, "export const REF_PREFIX = 'ref:';", "export const REF_PREFIX = 'ref#';"],
  // ---- handlers
  [H, "value.trim() === ''", "value === ''"],
  [H, '!Number.isInteger(value) ||', 'false ||'],
  [H, '|| value <= 0) throw', '|| value < 0) throw'],
  [H, "typeof value !== 'boolean'", 'false'],
  [H, 'Number(o) <= 255', 'true'],
  [H, 'Number(o) <= 255', 'Number(o) < 255'],
  [H, 'Number(m[5]) <= 32', 'true'],
  [H, 'Number(m[5]) <= 32', 'Number(m[5]) < 32'],
  [D, "['postgres', 'mysql', 'document'];", "['postgres', 'mysql', 'document', 'oracle'];"],
  [H, 'if (c.networkRefId !== undefined) cfg.networkRefId', 'if (false) cfg.networkRefId'],
  [H, "if (c.workloadType !== 'stateless' && c.workloadType !== 'stateful') throw", 'if (false) throw'],
  [H, 'if (c.workloadType !== undefined) {', 'if (false) {'],
  [H, 'if (c.credentialsRef !== undefined) cfg.credentialsRef', 'if (false) cfg.credentialsRef'],
  [H, 'if (!STORAGE_CLASSES.includes(storageClass)) throw', 'if (false) throw'],
  [H, 'if (c.publicAccessConfirmed !== undefined) cfg.publicAccessConfirmed', 'if (false) cfg.publicAccessConfirmed'],
  [H, "if (storageClass !== 'OBJECT' || c.sizeGb !== undefined) cfg.sizeGb", 'if (c.sizeGb !== undefined) cfg.sizeGb'],
  [H, "if (storageClass !== 'OBJECT' || c.sizeGb !== undefined) cfg.sizeGb", "if (storageClass !== 'OBJECT') cfg.sizeGb"],
  [H, "if (result.state === 'failed') {", 'if (false) {'],
  [H, 'if (result.id) await adapter.terminateInstance(result.id).catch(() => undefined);', ''],
  [H, 'if (!result.id) throw', 'if (false) throw'],
  [H, 'resolved: { ...(result.resolved ?? {}) }', 'resolved: {}'],
  [H, 'Object.prototype.hasOwnProperty.call(NODE_HANDLERS, type)', 'type in NODE_HANDLERS'],
  [H, 'r.resolveCompute(p).terminateInstance(id)', 'Promise.resolve()'],
  [H, 'r.resolveNetwork(p).deleteVirtualNetwork(id)', 'Promise.resolve()'],
  [H, 'r.resolveDatabase(p).deprovisionDatabase(id)', 'Promise.resolve()'],
  [H, 'r.resolveStorage(p).deprovisionStorage(id)', 'Promise.resolve()'],
  [H, 'adapter.provisionInstance(cfg, options)', 'adapter.provisionInstance(cfg, {})'],
  [H, 'createVirtualNetwork(cfg, options)', 'createVirtualNetwork(cfg, {})'],
  [H, 'provisionDatabase(cfg, options)', 'provisionDatabase(cfg, {})'],
  [H, 'provisionStorage(cfg, options)', 'provisionStorage(cfg, {})'],
  // ---- engine
  [E, 'if (failure) throw failure.error;', 'if (false) throw failure.error;'],
  [E, 'failure ??= { error: outcome.reason }', 'failure = { error: outcome.reason }'],
  [E, 'if (isNew) createdRecords.push(record);', 'createdRecords.push(record);'],
  [E, 'createdRecords.reverse()', 'createdRecords'],
  [E, '(isNew ? report.created : report.unchanged).push(id)', '(isNew ? report.unchanged : report.created).push(id)'],
  [E, 'resources.set(id, record.resourceId);', ''],
  [E, 'failures.length === 0\n', 'true\n'],
  [E, 'if (existing.digest !== digest) throw', 'if (false) throw'],
  [E, "status: 'skipped'", "status: 'success'"],
  [E, '      await this.state.put(record);', ''],
  [E, '      await handler.deprovision(this.registry, node.provider, outcome.resourceId).catch(() => undefined);', ''],
  [E, '        await this.state.remove(record.nodeId);', ''],
  [E, "status: 'failed', timestamp: now(), detail: messageOf(error) });\n      throw error;", "status: 'success', timestamp: now(), detail: messageOf(error) });\n      throw error;"],
  [E, 'const typed = handler.validate(node.id, config);', 'const typed = config as any;'],
  [E, 'if (checked.rejections.length > 0) await this.reject(checked.rejections);', 'if (false) await this.reject(checked.rejections);'],
  [E, "status: 'rejected'", "status: 'failed'"],
  [E, 'new Set(rejections.map((r) => r.nodeId)).size', 'rejections.length'],
  [E, 'detail: `${r.code}: ${r.reason}`', 'detail: r.reason'],
  [E, 'resolved: outcome.resolved };', 'resolved: {} };'],
  [E, 'requested: { ...(typed as Record<string, unknown>) }, resolved: outcome.resolved', 'requested: {}, resolved: outcome.resolved'],
  [E, 'resourceId: outcome.resourceId, evidence });', 'resourceId: outcome.resourceId });'],
  [E, 'resourceId: existing.resourceId, evidence: existing.evidence', 'resourceId: existing.resourceId'],
  [E, 'digestOf(kind, node.provider, config, options)', 'digestOf(kind, node.provider, config)'],
  [E, 'handler.provision(this.registry, node.provider, typed, options)', 'handler.provision(this.registry, node.provider, typed, {})'],
  [E, 'if (!rejected.has(n.node.id)) nodes.push', 'if (true) nodes.push'],
  [E, 'accepted: checked.rejections.length === 0', 'accepted: true'],
  [E, 'if (n.mode !== undefined) entry.mode = n.mode;', ''],
  [E, "n.kind === 'COMPUTE' && this.registry", 'true && this.registry'],
  [E, '.supportsDryRun) {', '.supportsDryRun || true) {'],
  [E, 'if (adapter.resolveSizing) entry.resolved', 'if (true) entry.resolved'],
  [E, 'private policy: EnginePolicy = {},', 'private policy: EnginePolicy = { allowPublicStorage: true },'],
  // ---- preflight
  [P, '  assertWellFormed(ir);\n', ''],
  [P, 'if (!ancestors.has(ref)) throw', 'if (false) throw'],
  [P, '    assertNoSecretValues(node.id, node.config);\n', ''],
  [P, '    assertNoSecretValues(node.id, node.providerOptions ?? {});\n', ''],
  [P, 'capability: contract.kinds[node.type].status', "capability: 'NATIVE'"],
  [P, 'mode: modeOf(node), options: { ...(node.providerOptions ?? {}) }', 'mode: modeOf(node), options: {}'],
  [P, 'registry.contractOf(n.node.provider), policy))', 'registry.contractOf(n.node.provider), {}))'],
  [P, 'const typed = NODE_HANDLERS[node.type].validate(node.id, node.config);', 'const typed: any = node.config;'],
  // ---- secret guard
  [S, 'if (!SECRET_FIELD.test(field)) continue;', 'if (false) continue;'],
  [S, '/password|passwd|secret|token|apikey|api_key|privatekey|private_key|credential/i', '/passwd|secret|token|apikey|api_key|privatekey|private_key|credential/i'],
  [S, '/password|passwd|secret|token|apikey|api_key|privatekey|private_key|credential/i', '/password|secret|token|apikey|api_key|privatekey|private_key|credential/i'],
  [S, '|secret|token|', '|token|'],
  [S, '|token|apikey', '|apikey'],
  [S, '|apikey|api_key|', '|api_key|'],
  [S, '|api_key|privatekey|', '|privatekey|'],
  [S, '|privatekey|private_key|', '|private_key|'],
  [S, '|private_key|credential/i', '|credential/'],
  [S, '|private_key|credential/i', '|private_key/i'],
  [S, "typeof value === 'string' && value.startsWith", 'value.startsWith'],
  [S, 'value.startsWith(SECRET_PREFIX) &&', 'true &&'],
  [S, ".trim() !== '';", '.length >= 0;'],
  [S, "export const SECRET_PREFIX = 'secret:';", "export const SECRET_PREFIX = 'secret#';"],
  // ---- capability evaluation
  [CE, "if (declared.status === 'UNSUPPORTED') {", 'if (false) {'],
  [CE, '    return rejections;\n  }\n\n  const mode = modeOf(node);', '  }\n\n  const mode = modeOf(node);'],
  [CE, "__t(declared.reasonKey ?? 'fabric.contract.reason.generic', { provider, kind }), declared.alternativeKeys ?? []);", "__t('fabric.contract.reason.generic', { provider, kind }), declared.alternativeKeys ?? []);"],
  [CE, "{ provider, kind }), declared.alternativeKeys ?? []);\n    return", "{ provider, kind }), []);\n    return"],
  [CE, "if (declared.status === 'CONDITIONAL') reject('MODE_REQUIRED'", "if (true) reject('MODE_REQUIRED'"],
  [CE, '} else if (!declared.modes.includes(mode)) {', '} else if (false) {'],
  [CE, "['fabric.contract.alt.set_provider_mode', ...(declared.alternativeKeys ?? [])]", "['fabric.contract.alt.set_provider_mode']"],
  [CE, "if (kind === 'DATABASE') {", 'if (false) {'],
  [CE, 'if (!contract.databaseEngines.includes(engine))', 'if (false)'],
  [CE, "if (kind === 'STORAGE') evaluateStorage", 'if (false) evaluateStorage'],
  [CE, 'if (!contract.storageClasses.includes(cfg.storageClass)) {', 'if (false) {'],
  [CE, "['fabric.contract.alt.use_supported_storage_class']);\n    return;", "['fabric.contract.alt.use_supported_storage_class']);"],
  [CE, 'if (!cfg.isPublic) return;', ''],
  [CE, 'if (!contract.publicStorageClasses.includes(cfg.storageClass)) {', 'if (false) {'],
  [CE, 'policy.allowPublicStorage !== true', 'false'],
  [CE, 'policy.allowPublicStorage !== true', 'policy.allowPublicStorage === false'],
  [CE, 'cfg.publicAccessConfirmed !== true', 'false'],
  [CE, 'values.length === 0 ? NONE : values.join', 'values.join'],
  [CE, "values.join(', ')", "values.join(',')"],
  [CE, 'alternativeKeys.map((key) => __t(key))', 'alternativeKeys.map((key) => key)'],
  // ---- contract declarations
  [CC, "storageClasses: ['OBJECT'],", "storageClasses: ['OBJECT', 'FILE'],"],
  [CC, "publicStorageClasses: ['OBJECT'],", 'publicStorageClasses: [],'],
  [CC, "databaseEngines: ['postgres', 'mysql'],", "databaseEngines: ['postgres', 'mysql', 'document'],"],
  [CC, "databaseEngines: ['mysql'],", "databaseEngines: ['mysql', 'postgres'],"],
  [CC, "modes: ['DEPLOYMENT', 'STATEFULSET']", "modes: ['DEPLOYMENT']"],
  [CC, "supportsDryRun: false", 'supportsDryRun: true'],
  [CC, "NETWORK: { status: 'UNSUPPORTED', modes: [], reasonKey: 'fabric.contract.reason.cpanel_network'", "NETWORK: { status: 'CONDITIONAL', modes: ['X'], reasonKey: 'fabric.contract.reason.cpanel_network'"],
  [CC, "DATABASE: { status: 'UNSUPPORTED', modes: [], reasonKey: 'fabric.contract.reason.linux_database'", "DATABASE: { status: 'CONDITIONAL', modes: ['X'], reasonKey: 'fabric.contract.reason.linux_database'"],
  [CC, "STORAGE: { status: 'NATIVE', modes: ['DIRECTORY'] }", "STORAGE: { status: 'CONDITIONAL', modes: ['DIRECTORY'] }"],
  [CC, "modes: ['EXISTING', 'NETWORKMANAGER', 'SYSTEMD_NETWORKD', 'NETPLAN']", "modes: ['EXISTING', 'NETWORKMANAGER', 'NETPLAN']"],
  // ---- contract assertion and registry
  [PC, "declared.status === 'UNSUPPORTED' && bound", "false && bound"],
  [PC, "declared.status !== 'UNSUPPORTED' && !bound", "false && !bound"],
  [PC, "declared.status === 'CONDITIONAL' && declared.modes.length === 0", "false && declared.modes.length === 0"],
  [PC, 'if (!declared) throw', 'if (false) throw'],
  [PC, 'if (!contract.provider) throw', 'if (false) throw'],
  [PC, 'adapters[kind] !== undefined', 'true'],
  [R, 'if (this.providers.has(contract.provider)) throw', 'if (false) throw'],
  [R, 'if (!adapter) throw', 'if (false) throw'],
  [R, 'public isRegistered(providerId: string): boolean {\n    return this.providers.has(providerId);', 'public isRegistered(providerId: string): boolean {\n    return true;'],
  [R, "if (!registration) throw new Error(__t('fabric.contract.provider_not_registered', { provider: providerId }));\n    return registration.contract;", 'return (registration as any).contract;'],
  // ---- state store
  [T, 'return record ? copyOf(record) : undefined;', 'return record;'],
  [T, 'this.records.set(record.nodeId, copyOf(record));', 'this.records.set(record.nodeId, record);'],
  [T, 'this.records.delete(nodeId);', ''],
  [T, 'requested: { ...record.evidence.requested }, resolved: { ...record.evidence.resolved }', 'requested: record.evidence.requested, resolved: { ...record.evidence.resolved }'],
  [T, 'requested: { ...record.evidence.requested }, resolved: { ...record.evidence.resolved }', 'requested: { ...record.evidence.requested }, resolved: record.evidence.resolved'],
];
let survived = 0;
for (const [file, from, to] of mutations) {
  const p = root + file;
  const original = fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n');
  if (!original.includes(from)) { console.log('ANCHOR MISSING', file, from.slice(0, 60)); continue; }
  fs.writeFileSync(p, original.replace(from, () => to));
  let out = '';
  try { out = execSync('node scratch\\run_qualification_gates.js', { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], timeout: 120000 }); } catch (e) { out = String(e.stdout || ''); }
  fs.writeFileSync(p, original);
  const line = out.split(/\r?\n/).find((l) => l.includes('QUALIFICATION RESULTS')) || 'NO RESULT (counted as caught: crash or hang)';
  const caught = !/\(0 failed\)/.test(line);
  if (!caught) survived++;
  console.log((caught ? 'caught   ' : 'SURVIVED ') + from.replace(/\s+/g, ' ').slice(0, 70).padEnd(72) + '=> ' + line.replace('QUALIFICATION RESULTS: ', ''));
}
console.log('survivors:', survived, 'of', mutations.length);
